-- Adel Abdallah, Senior Hydroinformatics Specialist at the WSWC, Feb 2019

--This is a Data Definition Language (DDL) script that
--generates a blank schema of the Water Data Exchange Data Model (WaDE)
-- for Microsoft SQL Server database.

-- Generated by Adel Abdallah Feb, 2019 based on WaDE XML design named WaDE2.0_schema_star generated by DbWrench V4.04 @ http://www.dbwrench.com/
-- WaDE All rights reserved. See BSD 3-Clause Licence @ https://github.com/WSWCWaterDataExchange/WaDE2.0/blob/master/LICENSE 

-- Open MySQL Workbench, Create a New SQL Tab for Executing queries
-- Simply copy all this script and paste into the new window of "create query"
-- Then click execute. The script should run successfully and create the 41 empty tables of WaDE

--------------------------------------------------------------------------------------------------
DROP SCHEMA IF EXISTS WaDE;

CREATE SCHEMA IF NOT EXISTS WaDE;

/***************************************************************************/
/*********************** CREATE WADE2.0_SCHEMA_STAR ************************/
/***************************************************************************/
USE WaDE;

CREATE TABLE AggregatedAmounts (
	AggregatedAmountID INT   NOT NULL PRIMARY KEY,
	AggregatedVariableMetadataID INT   NOT NULL,
	AmountMetadataID INT   NOT NULL,
	VariableSpecificID INT   NOT NULL,
	WaterSourceID INT   NOT NULL,
	ReportingUnitID INT   NOT NULL,
	MethodID INT   NOT NULL,
	TimeID INT   NOT NULL,
	OrganizationID	 INT   NOT NULL,
	Amount FLOAT   NOT NULL
);

CREATE TABLE AggregatedVariableMetadata (
	AggregatedVariableMetadataID INT   NOT NULL PRIMARY KEY,
	AmountUnitCV VARCHAR (100)  NOT NULL,
	AggregationStatisticCV VARCHAR (50)  NOT NULL,
	AggregationInterval VARCHAR (10)  NOT NULL,
	AggregationIntervalUnitCV VARCHAR (50)  NOT NULL,
	ReportYearStartMonth VARCHAR (10)  NOT NULL,
	ReportYearTypeCV VARCHAR (50)  NOT NULL
);

CREATE TABLE AllocationAmounts (
	AllocationAmountID INT   NOT NULL PRIMARY KEY,
	AllocationID INT   NOT NULL,
	SiteID INT   NOT NULL,
	MethodID INT   NOT NULL,
	TimeID INT   NOT NULL,
	WaterSourceID INT   NOT NULL,
	SiteVariableMetadataID INT   NOT NULL,
	VariableSpecificID INT   NOT NULL,
	OrganizationID	 INT   NOT NULL,
	AmountMetadataID INT   NULL,
	AllocationDutyAmount FLOAT   NULL,
	AllocationAmount FLOAT   NOT NULL,
	AllocationMaximum FLOAT   NULL
);

CREATE TABLE Allocations (
	AllocationID INT   NOT NULL PRIMARY KEY,
	NativeAllocationID VARCHAR (250)  NULL,
	AllocationUID VARCHAR (50)  NOT NULL,
	AllocationOwner VARCHAR (255)  NOT NULL,
	AllocationApplicationDate DATE   NULL,
	AllocationPriorityDate DATE   NOT NULL,
	AllocationLegalStatusCodeCV VARBINARY (50)  NOT NULL,
	AllocationExpirationDate DATE   NULL,
	AllocationChangeApplicationIndicator VARCHAR (100)  NULL,
	LegacyAllocationIDs VARCHAR (100)  NULL,
	AllocationBasisCV BIGINT   NULL,
	AllocationAcreage BIGINT   NULL
);

CREATE TABLE AmountMetadata (
	AmountMetadataID INT   NOT NULL PRIMARY KEY,
	BeneficialUseCategory VARCHAR (255)  NULL,
	PrimaryUseCategory VARCHAR (255)  NULL,
	USGSCategoryCV VARCHAR (255)  NULL,
	SDWISIdentifier VARCHAR (255)  NULL,
	NAICSCodeCV VARCHAR (255)  NULL,
	PopulationServed FLOAT   NULL,
	IrrigatedAcreage FLOAT   NULL,
	IrrigationMethod VARCHAR (100)  NULL,
	CropType VARCHAR (100)  NULL,
	PowerGeneratedGWh FLOAT   NULL,
	Geometry BLOB   NULL,
	InterbasinTransferFromID VARCHAR (50)  NULL,
	InterbasinTransferToID VARCHAR (255)  NULL
);

CREATE TABLE CVs_AggregationStatistic (
	Name VARCHAR (255)  NOT NULL PRIMARY KEY,
	Term VARCHAR (255)  NOT NULL,
	Definition VARCHAR (5000)  NULL,
	Category VARCHAR (255)  NULL,
	SourceVocabularyURI	 VARCHAR (255)  NULL
);

CREATE TABLE CVs_EPSGCode (
	Name VARCHAR (255)  NOT NULL PRIMARY KEY,
	Term VARCHAR (255)  NOT NULL,
	Definition VARCHAR (5000)  NULL,
	Category VARCHAR (255)  NULL,
	SourceVocabularyURI	 VARCHAR (255)  NULL
);

CREATE TABLE CVs_GNISCode (
	Name VARCHAR (255)  NOT NULL PRIMARY KEY,
	Term VARCHAR (255)  NOT NULL,
	Definition VARCHAR (5000)  NULL,
	Category VARCHAR (255)  NULL,
	SourceVocabularyURI	 VARCHAR (255)  NULL
);

CREATE TABLE CVs_LegalStatusCode (
	Name VARCHAR (255)  NOT NULL PRIMARY KEY,
	Term VARCHAR (255)  NOT NULL,
	Definition VARCHAR (5000)  NULL,
	Category VARCHAR (255)  NULL,
	SourceVocabularyURI	 VARCHAR (255)  NULL
);

CREATE TABLE CVs_MethodType (
	Name VARCHAR (255)  NOT NULL PRIMARY KEY,
	Term VARCHAR (255)  NOT NULL,
	Definition VARCHAR (5000)  NULL,
	Category VARCHAR (255)  NULL,
	SourceVocabularyURI	 VARCHAR (255)  NULL
);

CREATE TABLE CVs_NAICSCode (
	Name VARCHAR (255)  NOT NULL PRIMARY KEY,
	Term VARCHAR (255)  NOT NULL,
	Definition VARCHAR (5000)  NULL,
	Category VARCHAR (255)  NULL,
	SourceVocabularyURI	 VARCHAR (255)  NULL
);

CREATE TABLE CVs_NHDNetworkStatus (
	Name VARCHAR (255)  NOT NULL PRIMARY KEY,
	Term VARCHAR (255)  NOT NULL,
	Definition VARCHAR (5000)  NULL,
	Category VARCHAR (255)  NULL,
	SourceVocabularyURI	 VARCHAR (255)  NULL
);

CREATE TABLE CVs_NHDProduct (
	Name VARCHAR (255)  NOT NULL PRIMARY KEY,
	Term VARCHAR (255)  NOT NULL,
	Definition VARCHAR (5000)  NULL,
	Category VARCHAR (255)  NULL,
	SourceVocabularyURI	 VARCHAR (255)  NULL
);

CREATE TABLE CVs_RegulatoryStatus (
	Name VARCHAR (255)  NOT NULL PRIMARY KEY,
	Term VARCHAR (255)  NOT NULL,
	Definition VARCHAR (5000)  NULL,
	Category VARCHAR (255)  NULL,
	SourceVocabularyURI	 VARCHAR (255)  NULL
);

CREATE TABLE CVs_ReportingUnitType (
	Name VARCHAR (255)  NOT NULL PRIMARY KEY,
	Term VARCHAR (255)  NOT NULL,
	Definition VARCHAR (5000)  NULL,
	Category VARCHAR (255)  NULL,
	SourceVocabularyURI	 VARCHAR (255)  NULL
);

CREATE TABLE CVs_ReportYearCV (
	Name VARCHAR (255)  NOT NULL PRIMARY KEY,
	Term VARCHAR (255)  NOT NULL,
	Definition VARCHAR (5000)  NULL,
	Category VARCHAR (255)  NULL,
	SourceVocabularyURI	 VARCHAR (255)  NULL
);

CREATE TABLE CVs_ReportYearType (
	Name VARCHAR (255)  NOT NULL PRIMARY KEY,
	Term VARCHAR (255)  NOT NULL,
	Definition VARCHAR (5000)  NULL,
	Category VARCHAR (255)  NULL,
	SourceVocabularyURI	 VARCHAR (255)  NULL
);

CREATE TABLE CVs_Units (
	Name VARCHAR (255)  NOT NULL PRIMARY KEY,
	Term VARCHAR (255)  NOT NULL,
	Definition VARCHAR (5000)  NULL,
	Category VARCHAR (255)  NULL,
	SourceVocabularyURI	 VARCHAR (255)  NULL
);

CREATE TABLE CVs_USGSCategory (
	Name VARCHAR (255)  NOT NULL PRIMARY KEY,
	Term VARCHAR (255)  NOT NULL,
	Definition VARCHAR (5000)  NULL,
	Category VARCHAR (255)  NULL,
	SourceVocabularyURI	 VARCHAR (255)  NULL
);

CREATE TABLE CVs_Variable (
	Name VARCHAR (255)  NOT NULL PRIMARY KEY,
	Term VARCHAR (255)  NOT NULL,
	Definition VARCHAR (5000)  NULL,
	Category VARCHAR (255)  NULL,
	SourceVocabularyURI	 VARCHAR (255)  NULL
);

CREATE TABLE CVs_VerticalDatumEPSGCode (
	Name VARCHAR (255)  NOT NULL PRIMARY KEY,
	Term VARCHAR (255)  NOT NULL,
	Definition VARCHAR (5000)  NULL,
	Category VARCHAR (255)  NULL,
	SourceVocabularyURI	 VARCHAR (255)  NULL
);

CREATE TABLE CVs_WaterAllocationBasis (
	Name VARCHAR (255)  NOT NULL PRIMARY KEY,
	Term VARCHAR (255)  NOT NULL,
	Definition VARCHAR (5000)  NULL,
	Category VARCHAR (255)  NULL,
	SourceVocabularyURI	 VARCHAR (255)  NULL
);

CREATE TABLE CVs_WaterAllocationBasis_dup (
	Name VARCHAR (255)  NOT NULL PRIMARY KEY,
	Term VARCHAR (255)  NOT NULL,
	Definition VARCHAR (5000)  NULL,
	Category VARCHAR (255)  NULL,
	SourceVocabularyURI	 VARCHAR (255)  NULL
);

CREATE TABLE CVs_WaterQualityIndicator (
	Name VARCHAR (255)  NOT NULL PRIMARY KEY,
	Term VARCHAR (255)  NOT NULL,
	Definition VARCHAR (5000)  NULL,
	Category VARCHAR (255)  NULL,
	SourceVocabularyURI	 VARCHAR (255)  NULL
);

CREATE TABLE CVs_WaterSourceType (
	Name VARCHAR (255)  NOT NULL PRIMARY KEY,
	Term VARCHAR (255)  NOT NULL,
	Definition VARCHAR (5000)  NULL,
	Category VARCHAR (255)  NULL,
	SourceVocabularyURI	 VARCHAR (255)  NULL
);

CREATE TABLE Methods (
	MethodID INT   NOT NULL PRIMARY KEY,
	MethodUID VARCHAR (100)  NOT NULL,
	MethodName VARCHAR (50)  NOT NULL,
	MethodDescription TEXT   NOT NULL,
	MethodNEMILink VARCHAR (100)  NULL,
	ApplicableResourceTypeCV VARCHAR (100)  NOT NULL,
	MethodTypeCV VARCHAR (50)  NOT NULL,
	DataCoverageValue VARCHAR (100)  NULL,
	DataQualityValueCV VARCHAR (50)  NULL,
	DataConfidenceValue VARCHAR (50)  NULL
);

CREATE TABLE NHDMetadata (
	NHDMetadataID INT   NOT NULL PRIMARY KEY,
	NHDNetworkStatusCV VARCHAR (50)  NOT NULL,
	NHDProductCV VARCHAR (50)  NULL,
	NHDUpdateDate DATE   NULL,
	NHDReachCode VARCHAR (50)  NULL,
	NHDMeasureNumber VARCHAR (50)  NULL
);

CREATE TABLE Organizations (
	OrganizationID	 INT   NOT NULL PRIMARY KEY,
	OrganizationUID VARBINARY (255)  NOT NULL,
	OrganizationName VARCHAR (255)  NOT NULL,
	OrganizationPurview VARCHAR (255)  NULL,
	OrganizationWebsite VARCHAR (255)  NULL,
	OrganizationPhoneNumber VARCHAR (255)  NULL,
	OrganizationContactName VARCHAR (255)  NULL,
	OrganizationContactEmail VARCHAR   NULL
);

CREATE TABLE RegulatoryOverlay (
	RegulatoryOverlayID INT   NOT NULL PRIMARY KEY,
	NativeRegulatoryOverlayID VARCHAR (255)  NULL,
	RegulatoryOverlayUID VARCHAR (255)  NULL,
	RegulatoryName VARCHAR (50)  NOT NULL,
	RegulatoryDescription TEXT   NOT NULL,
	RegulatoryStatusCV VARCHAR (50)  NOT NULL,
	OversightAgency VARCHAR (250)  NOT NULL,
	RegulatoryStatute VARCHAR (500)  NULL,
	RegulatoryStatuteLink VARCHAR (500)  NULL,
	TimeframeStart DATE   NOT NULL,
	TimeframeEnd DATE   NOT NULL,
	ReportYearTypeCV VARCHAR (10)  NOT NULL,
	ReportYearStartMonth VARCHAR (5)  NOT NULL
);

CREATE TABLE RegulatoryReportingUnits (
	BridgeID INT   NOT NULL PRIMARY KEY,
	RegulatoryOverlayID INT   NOT NULL,
	ReportingUnitID INT   NOT NULL,
	OrganizationID	 INT   NOT NULL,
	ReportYearCV VARCHAR (4)  NULL,
	DataPublicationDate DATE   NOT NULL
);

CREATE TABLE ReportingUnits (
	ReportingUnitID INT   NOT NULL PRIMARY KEY,
	ReportingUnitNativeID VARCHAR (250)  NULL,
	ReportingUnitUID VARCHAR (255)  NOT NULL,
	ReportingUnitName VARCHAR (255)  NOT NULL,
	ReportingUnitTypeCV VARCHAR (20)  NOT NULL,
	ReportingUnitUpdateDate DATE   NULL,
	ReportingUnitProductVersion VARCHAR (100)  NULL,
	StateCV VARCHAR (50)  NOT NULL,
	EPSGCodeCV VARBINARY (50)  NULL,
	VerticalDatumEPSGCodeCV VARCHAR (50)  NULL,
	Geometry BLOB   NULL
);

CREATE TABLE Sites (
	SiteID INT   NOT NULL PRIMARY KEY,
	SiteUID VARCHAR (55)  NOT NULL,
	NativeSiteID VARCHAR (50)  NULL,
	SiteName VARCHAR (500)  NOT NULL,
	SiteTypeCV VARCHAR (100)  NULL,
	Longitude VARCHAR (50)  NOT NULL,
	Latitude VARCHAR (50)  NOT NULL,
	Geometry BLOB   NULL,
	VerticalDatumEPSGCodeCV VARCHAR (50)  NOT NULL,
	CoordinateMethodCV VARCHAR (100)  NOT NULL,
	CoordinateAccuracy VARCHAR (255)  NULL,
	GNISCodeCV VARCHAR (50)  NULL,
	NHDMetadataID INT   NULL
);

CREATE TABLE SiteVariableAmounts (
	SiteVariableAmountID INT   NOT NULL PRIMARY KEY,
	AllocationID INT   NOT NULL,
	TimeID INT   NOT NULL,
	SiteID INT   NOT NULL,
	MethodID INT   NOT NULL,
	WaterSourceID INT   NOT NULL,
	SiteVariableMetadataID INT   NOT NULL,
	VariableSpecificID INT   NOT NULL,
	OrganizationID	 INT   NOT NULL,
	AmountMetadataID INT   NULL,
	Amount FLOAT   NOT NULL
);

CREATE TABLE SiteVariableMetadata (
	SiteVariableMetadataID INT   NOT NULL PRIMARY KEY,
	SiteVariableMetadataUID VARCHAR (500)  NULL,
	AmountUnitCV VARCHAR (100)  NOT NULL,
	AggregationStatisticCV VARCHAR (50)  NOT NULL,
	AggregationInterval VARCHAR (5)  NOT NULL,
	AggregationIntervalUnitCV VARCHAR (50)  NOT NULL,
	ReportYearStartMonth VARCHAR (5)  NULL,
	ReportYearTypeCV VARCHAR (50)  NULL,
	MaximumAmountUnitCV VARCHAR (255)  NULL
);

CREATE TABLE Time_dim (
	TimeID INT   NOT NULL PRIMARY KEY,
	ReportYearCV VARCHAR (4)  NULL,
	TimeframeStart DATE   NULL,
	TimeframeEnd DATE   NULL,
	DataPublicationDate DATE   NULL
);

CREATE TABLE Variables (
	VariableSpecificID INT   NOT NULL PRIMARY KEY,
	VariableSpecificUID VARCHAR (255)  NULL,
	VariableSpecificCV VARCHAR (255)  NOT NULL,
	VariableCV VARCHAR (255)  NOT NULL,
	AggregationStatisticCV VARCHAR (50)  NULL,
	AggregationInterval  NUMERIC (10)  NULL,
	AggregationIntervalUnitCV  VARCHAR (50)  NULL,
	ReportYearStartMonth  VARCHAR (10)  NULL,
	ReportYearTypeCV  VARCHAR (10)  NULL,
	AmountUnitCV VARCHAR (10)  NULL,
	MaximumAmountUnitCV NUMERIC (10)  NULL
);

CREATE TABLE WaterSources (
	WaterSourceID INT   NOT NULL PRIMARY KEY,
	WaterSourceUID VARCHAR (100)  NOT NULL,
	WaterSourceNativeID VARCHAR (255)  NULL,
	WaterSourceName VARCHAR (255)  NULL,
	WaterSourceTypeCV VARCHAR (100)  NOT NULL,
	WaterQualityIndicatorCV VARCHAR (100)  NOT NULL,
	Geometry BLOB   NULL,
	GNISFeatureNameCV VARCHAR (255)  NULL
);


ALTER TABLE AggregatedAmounts ADD CONSTRAINT fk_AggregatedAmounts_AggregatedVariableMetadata
FOREIGN KEY (AggregatedVariableMetadataID) REFERENCES AggregatedVariableMetadata (AggregatedVariableMetadataID)
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE AggregatedAmounts ADD CONSTRAINT fk_AggregatedAmounts_AmountsMetadata
FOREIGN KEY (AmountMetadataID) REFERENCES AmountMetadata (AmountMetadataID)
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE AggregatedAmounts ADD CONSTRAINT fk_AggregatedAmounts_Methods
FOREIGN KEY (MethodID) REFERENCES Methods (MethodID)
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE AggregatedAmounts ADD CONSTRAINT fk_AggregatedAmounts_Organizations
FOREIGN KEY (OrganizationID	) REFERENCES Organizations (OrganizationID	)
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE AggregatedAmounts ADD CONSTRAINT fk_AggregatedAmounts_ReportingUnits
FOREIGN KEY (ReportingUnitID) REFERENCES ReportingUnits (ReportingUnitID)
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE AggregatedAmounts ADD CONSTRAINT fk_AggregatedAmounts_Time_dim
FOREIGN KEY (TimeID) REFERENCES Time_dim (TimeID)
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE AggregatedAmounts ADD CONSTRAINT fk_AggregatedAmounts_VariablesSpecific
FOREIGN KEY (VariableSpecificID) REFERENCES Variables (VariableSpecificID)
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE AggregatedAmounts ADD CONSTRAINT fk_AggregatedAmounts_WaterSources
FOREIGN KEY (WaterSourceID) REFERENCES WaterSources (WaterSourceID)
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE AllocationAmounts ADD CONSTRAINT fk_WaterAllocationAmounts_AmountMetadata
FOREIGN KEY (AmountMetadataID) REFERENCES AmountMetadata (AmountMetadataID)
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE AllocationAmounts ADD CONSTRAINT fk_WaterAllocationAmounts_Methods
FOREIGN KEY (MethodID) REFERENCES Methods (MethodID)
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE AllocationAmounts ADD CONSTRAINT fk_WaterAllocationAmounts_Organizations
FOREIGN KEY (OrganizationID	) REFERENCES Organizations (OrganizationID	)
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE AllocationAmounts ADD CONSTRAINT fk_WaterAllocationAmounts_Sites
FOREIGN KEY (SiteID) REFERENCES Sites (SiteID)
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE AllocationAmounts ADD CONSTRAINT fk_WaterAllocationAmounts_SiteVariableMetadata
FOREIGN KEY (SiteVariableMetadataID) REFERENCES SiteVariableMetadata (SiteVariableMetadataID)
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE AllocationAmounts ADD CONSTRAINT fk_WaterAllocationAmounts_Time_dim
FOREIGN KEY (TimeID) REFERENCES Time_dim (TimeID)
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE AllocationAmounts ADD CONSTRAINT fk_WaterAllocationAmounts_VariablesSpecific
FOREIGN KEY (VariableSpecificID) REFERENCES Variables (VariableSpecificID)
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE AllocationAmounts ADD CONSTRAINT fk_WaterAllocationAmounts_WaterAllocations
FOREIGN KEY (AllocationID) REFERENCES Allocations (AllocationID)
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE AllocationAmounts ADD CONSTRAINT fk_WaterAllocationAmounts_WaterSources
FOREIGN KEY (WaterSourceID) REFERENCES WaterSources (WaterSourceID)
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE RegulatoryReportingUnits ADD CONSTRAINT fk_RegulatoryReportingUnits_Organizations
FOREIGN KEY (OrganizationID	) REFERENCES Organizations (OrganizationID	)
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE RegulatoryReportingUnits ADD CONSTRAINT fk_RegulatoryReportingUnits_RegulatoryOverlay
FOREIGN KEY (RegulatoryOverlayID) REFERENCES RegulatoryOverlay (RegulatoryOverlayID)
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE RegulatoryReportingUnits ADD CONSTRAINT fk_RegulatoryReportingUnits_ReportingUnits
FOREIGN KEY (ReportingUnitID) REFERENCES ReportingUnits (ReportingUnitID)
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE Sites ADD CONSTRAINT fk_Sites_NHDMetadata
FOREIGN KEY (NHDMetadataID) REFERENCES NHDMetadata (NHDMetadataID)
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE SiteVariableAmounts ADD CONSTRAINT fk_SiteVariableAmounts_AmountMetadata
FOREIGN KEY (AmountMetadataID) REFERENCES AmountMetadata (AmountMetadataID)
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE SiteVariableAmounts ADD CONSTRAINT fk_SiteVariableAmounts_Methods
FOREIGN KEY (MethodID) REFERENCES Methods (MethodID)
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE SiteVariableAmounts ADD CONSTRAINT fk_SiteVariableAmounts_Organizations
FOREIGN KEY (OrganizationID	) REFERENCES Organizations (OrganizationID	)
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE SiteVariableAmounts ADD CONSTRAINT fk_SiteVariableAmounts_Sites
FOREIGN KEY (SiteID) REFERENCES Sites (SiteID)
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE SiteVariableAmounts ADD CONSTRAINT fk_SiteVariableAmounts_SiteVariableMetadata
FOREIGN KEY (SiteVariableMetadataID) REFERENCES SiteVariableMetadata (SiteVariableMetadataID)
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE SiteVariableAmounts ADD CONSTRAINT fk_SiteVariableAmounts_Time_dim
FOREIGN KEY (TimeID) REFERENCES Time_dim (TimeID)
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE SiteVariableAmounts ADD CONSTRAINT fk_SiteVariableAmounts_VariablesSpecific
FOREIGN KEY (VariableSpecificID) REFERENCES Variables (VariableSpecificID)
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE SiteVariableAmounts ADD CONSTRAINT fk_SiteVariableAmounts_WaterAllocations
FOREIGN KEY (AllocationID) REFERENCES Allocations (AllocationID)
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE SiteVariableAmounts ADD CONSTRAINT fk_SiteVariableAmounts_WaterSources
FOREIGN KEY (WaterSourceID) REFERENCES WaterSources (WaterSourceID)
ON UPDATE NO ACTION ON DELETE NO ACTION;