-- Adel Abdallah, Senior Hydroinformatics Specialist at the WSWC, Feb 2019

--This is a Data Definition Language (DDL) script that
--generates a blank schema of the Water Data Exchange Data Model (WaDE)
-- for Microsoft SQL Server database.

-- Generated by Adel Abdallah Feb, 2019 based on WaDE XML design named WaDE2.0_schema_star generated by DbWrench V4.04 @ http://www.dbwrench.com/
-- WaDE All rights reserved. See BSD 3-Clause Licence @ https://github.com/WSWCWaterDataExchange/WaDE2.0/blob/master/LICENSE 

--Use the SQLite Manager Add-on to Mozilla Firefox
--Create a new empty database. Click on the Execute SQL button and delete the text "SELECT * FROM tablename"
--Simply copy all this script and paste into this Execute SQL window
--Then click Run SQL. The script should run successfully and create the 41 empty tables of WaDE

--------------------------------------------------------------------------------------------------
/***************************************************************************/
/*********************** CREATE WADE2.0_SCHEMA_STAR ************************/
/***************************************************************************/

CREATE TABLE AggBridge_BeneficialUses_fact (
	AggBridgeID INTEGER   NOT NULL PRIMARY KEY,
	BeneficialUseID INTEGER   NOT NULL,
	AggregatedAmountID INTEGER   NOT NULL,
	FOREIGN KEY (AggregatedAmountID) REFERENCES AggregatedAmounts_fact (AggregatedAmountID)
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY (BeneficialUseID) REFERENCES BeneficialUses_dim (BeneficialUseID)
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE AggregatedAmounts_fact (
	AggregatedAmountID INTEGER   NOT NULL PRIMARY KEY,
	OrganizationID INTEGER   NOT NULL,
	ReportingUnitID INTEGER   NOT NULL,
	VariableSpecificID INTEGER   NOT NULL,
	BeneficialUseID INTEGER   NOT NULL,
	WaterSourceID INTEGER   NOT NULL,
	MethodID INTEGER   NOT NULL,
	TimeframeStartID INTEGER   NULL,
	TimeframeEndID INTEGER   NULL,
	DataPublicationDate INTEGER   NULL,
	ReportYear VARCHAR (4)  NULL,
	Amount FLOAT   NOT NULL,
	PopulationServed FLOAT   NULL,
	PowerGeneratedGWh FLOAT   NULL,
	IrrigatedAcreage FLOAT   NULL,
	InterbasinTransferToID VARCHAR (100)  NULL,
	InterbasinTransferFromID VARCHAR (100)  NULL,
	FOREIGN KEY (TimeframeEndID) REFERENCES Date_dim (DateID)
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY (DataPublicationDate) REFERENCES Date_dim (DateID)
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY (TimeframeStartID) REFERENCES Date_dim (DateID)
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY (BeneficialUseID) REFERENCES BeneficialUses_dim (BeneficialUseID)
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY (ReportYear) REFERENCES CVs_ReportYearCV (Name)
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY (MethodID) REFERENCES Methods_dim (MethodID)
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY (OrganizationID) REFERENCES Organizations_dim (OrganizationID)
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY (ReportingUnitID) REFERENCES ReportingUnits_dim (ReportingUnitID)
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY (VariableSpecificID) REFERENCES Variables_dim (VariableSpecificID)
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY (WaterSourceID) REFERENCES WaterSources_dim (WaterSourceID)
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE AllocationAmounts_fact (
	AllocationAmountID INTEGER   NOT NULL PRIMARY KEY,
	OrganizationID INTEGER   NOT NULL,
	AllocationID INTEGER   NOT NULL,
	SiteID INTEGER   NOT NULL,
	VariableSpecificID INTEGER   NOT NULL,
	BeneficialUsesID INTEGER   NOT NULL,
	WaterSourceID INTEGER   NOT NULL,
	MethodID INTEGER   NOT NULL,
	TimeframeStartDateID INTEGER   NOT NULL,
	TimeframeEndDateID INTEGER   NOT NULL,
	DataPublicationDateID INTEGER   NOT NULL,
	ReportYear VARCHAR (4)  NOT NULL,
	AllocationCropDutyAmount FLOAT   NULL,
	AllocationAmount FLOAT   NULL,
	AllocationMaximum FLOAT   NULL,
	PopulationServed FLOAT   NULL,
	PowerGeneratedGWh FLOAT   NULL,
	IrrigatedAcreage FLOAT   NULL,
	AllocationCommunityWaterSupplySystem VARCHAR (250)  NULL,
	SDWISIdentifier VARCHAR (250)  NULL,
	InterbasinTransferFromID VARCHAR (250)  NULL,
	InterbasinTransferToID VARCHAR (250)  NULL,
	Geometry BLOB   NULL,
	FOREIGN KEY (AllocationID) REFERENCES Allocations_dim (AllocationID)
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY (BeneficialUsesID) REFERENCES BeneficialUses_dim (BeneficialUseID)
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY (ReportYear) REFERENCES CVs_ReportYearCV (Name)
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY (TimeframeEndDateID) REFERENCES Date_dim (DateID)
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY (TimeframeStartDateID) REFERENCES Date_dim (DateID)
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY (DataPublicationDateID) REFERENCES Date_dim (DateID)
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY (MethodID) REFERENCES Methods_dim (MethodID)
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY (OrganizationID) REFERENCES Organizations_dim (OrganizationID)
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY (SiteID) REFERENCES Sites_dim (SiteID)
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY (VariableSpecificID) REFERENCES Variables_dim (VariableSpecificID)
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY (WaterSourceID) REFERENCES WaterSources_dim (WaterSourceID)
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE AllocationBridge_BeneficialUses_fact (
	AllocationBridgeID INTEGER   NOT NULL PRIMARY KEY,
	BeneficialUseID INTEGER   NOT NULL,
	AllocationAmountID INTEGER   NOT NULL,
	FOREIGN KEY (AllocationAmountID) REFERENCES AllocationAmounts_fact (AllocationAmountID)
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY (BeneficialUseID) REFERENCES BeneficialUses_dim (BeneficialUseID)
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE Allocations_dim (
	AllocationID INTEGER   NOT NULL PRIMARY KEY,
	AllocationUUID VARCHAR (50)  NOT NULL,
	AllocationNativeID VARCHAR (250)  NOT NULL,
	AllocationOwner VARCHAR (255)  NOT NULL,
	AllocationBasisCV VARCHAR (250)  NULL,
	AllocationLegalStatusCV VARCHAR (50)  NOT NULL,
	AllocationApplicationDate INTEGER   NULL,
	AllocationPriorityDate INTEGER   NOT NULL,
	AllocationExpirationDate INTEGER   NULL,
	AllocationChangeApplicationIndicator VARCHAR (100)  NULL,
	LegacyAllocationIDs VARCHAR (100)  NULL,
	FOREIGN KEY (AllocationApplicationDate) REFERENCES Date_dim (DateID)
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY (AllocationExpirationDate) REFERENCES Date_dim (DateID)
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY (AllocationPriorityDate) REFERENCES Date_dim (DateID)
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE BeneficialUses_dim (
	BeneficialUseID INTEGER   NOT NULL PRIMARY KEY,
	BeneficialUseCategory VARCHAR (500)  NOT NULL,
	PrimaryUseCategory VARCHAR (250)  NULL,
	USGSCategoryNameCV VARCHAR (250)  NULL,
	NAICSCodeNameCV VARCHAR (250)  NULL,
	FOREIGN KEY (NAICSCodeNameCV) REFERENCES CVs_NAICSCode (Name)
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY (USGSCategoryNameCV) REFERENCES CVs_USGSCategory (Name)
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE CVs_AggregationStatistic (
	Name VARCHAR (250)  NOT NULL PRIMARY KEY,
	Term VARCHAR (250)  NOT NULL,
	Definition VARCHAR (5000)  NULL,
	Category VARCHAR (250)  NULL,
	SourceVocabularyURI	 VARCHAR (250)  NULL
);

CREATE TABLE CVs_CropType (
	Name VARCHAR (250)  NOT NULL PRIMARY KEY,
	Term VARCHAR (250)  NULL,
	Definition VARCHAR (5000)  NULL,
	Category VARCHAR (250)  NULL,
	SourceVocabularyURI VARCHAR (250)  NULL
);

CREATE TABLE CVs_EPSGCode (
	Name VARCHAR (250)  NOT NULL PRIMARY KEY,
	Term VARCHAR (250)  NOT NULL,
	Definition VARCHAR (5000)  NULL,
	Category VARCHAR (250)  NULL,
	SourceVocabularyURI	 VARCHAR (250)  NULL
);

CREATE TABLE CVs_GNISFeatureName (
	Name VARCHAR (250)  NOT NULL PRIMARY KEY,
	Term VARCHAR (250)  NOT NULL,
	Definition VARCHAR (5000)  NULL,
	Category VARCHAR (250)  NULL,
	SourceVocabularyURI	 VARCHAR (250)  NULL
);

CREATE TABLE CVs_IrrigationMethod (
	Name VARCHAR (250)  NOT NULL PRIMARY KEY,
	Term VARCHAR (250)  NULL,
	Definition VARCHAR (5000)  NULL,
	Category VARCHAR (250)  NULL,
	SourceVocabularyURI VARCHAR (250)  NULL
);

CREATE TABLE CVs_LegalStatus (
	Name VARCHAR (250)  NOT NULL PRIMARY KEY,
	Term VARCHAR (250)  NOT NULL,
	Definition VARCHAR (5000)  NULL,
	Category VARCHAR (250)  NULL,
	SourceVocabularyURI	 VARCHAR (250)  NULL
);

CREATE TABLE CVs_MethodType (
	Name VARCHAR (250)  NOT NULL PRIMARY KEY,
	Term VARCHAR (250)  NOT NULL,
	Definition VARCHAR (5000)  NULL,
	Category VARCHAR (250)  NULL,
	SourceVocabularyURI	 VARCHAR (250)  NULL
);

CREATE TABLE CVs_NAICSCode (
	Name VARCHAR (250)  NOT NULL PRIMARY KEY,
	Term VARCHAR (250)  NOT NULL,
	Definition VARCHAR (5000)  NULL,
	Category VARCHAR (250)  NULL,
	SourceVocabularyURI	 VARCHAR (250)  NULL
);

CREATE TABLE CVs_NHDNetworkStatus (
	Name VARCHAR (250)  NOT NULL PRIMARY KEY,
	Term VARCHAR (250)  NOT NULL,
	Definition VARCHAR (5000)  NULL,
	Category VARCHAR (250)  NULL,
	SourceVocabularyURI	 VARCHAR (250)  NULL
);

CREATE TABLE CVs_NHDProduct (
	Name VARCHAR (250)  NOT NULL PRIMARY KEY,
	Term VARCHAR (250)  NOT NULL,
	Definition VARCHAR (5000)  NULL,
	Category VARCHAR (250)  NULL,
	SourceVocabularyURI	 VARCHAR (250)  NULL
);

CREATE TABLE CVs_RegulatoryStatus (
	Name VARCHAR (250)  NOT NULL PRIMARY KEY,
	Term VARCHAR (250)  NOT NULL,
	Definition VARCHAR (5000)  NULL,
	Category VARCHAR (250)  NULL,
	SourceVocabularyURI	 VARCHAR (250)  NULL
);

CREATE TABLE CVs_ReportingUnitType (
	Name VARCHAR (250)  NOT NULL PRIMARY KEY,
	Term VARCHAR (250)  NOT NULL,
	Definition VARCHAR (5000)  NULL,
	Category VARCHAR (250)  NULL,
	SourceVocabularyURI	 VARCHAR (250)  NULL
);

CREATE TABLE CVs_ReportYearCV (
	Name VARCHAR (4)  NOT NULL PRIMARY KEY,
	Term VARCHAR (250)  NOT NULL,
	Definition VARCHAR (5000)  NULL,
	Category VARCHAR (250)  NULL,
	SourceVocabularyURI	 VARCHAR (250)  NULL
);

CREATE TABLE CVs_ReportYearType (
	Name VARCHAR (250)  NOT NULL PRIMARY KEY,
	Term VARCHAR (250)  NOT NULL,
	Definition VARCHAR (5000)  NULL,
	Category VARCHAR (250)  NULL,
	SourceVocabularyURI	 VARCHAR (250)  NULL
);

CREATE TABLE CVs_Units (
	Name VARCHAR (250)  NOT NULL PRIMARY KEY,
	Term VARCHAR (250)  NOT NULL,
	Definition VARCHAR (5000)  NULL,
	Category VARCHAR (250)  NULL,
	SourceVocabularyURI	 VARCHAR (250)  NULL
);

CREATE TABLE CVs_USGSCategory (
	Name VARCHAR (250)  NOT NULL PRIMARY KEY,
	Term VARCHAR (250)  NOT NULL,
	Definition VARCHAR (5000)  NULL,
	Category VARCHAR (250)  NULL,
	SourceVocabularyURI	 VARCHAR (250)  NULL
);

CREATE TABLE CVs_Variable (
	Name VARCHAR (250)  NOT NULL PRIMARY KEY,
	Term VARCHAR (250)  NOT NULL,
	Definition VARCHAR (5000)  NULL,
	Category VARCHAR (250)  NULL,
	SourceVocabularyURI	 VARCHAR (250)  NULL
);

CREATE TABLE CVs_VariableSpecific (
	Name VARCHAR (250)  NOT NULL PRIMARY KEY,
	Term VARCHAR (250)  NOT NULL,
	Definition VARCHAR (5000)  NULL,
	Category VARCHAR (250)  NULL,
	SourceVocabularyURI VARCHAR (250)  NULL
);

CREATE TABLE CVs_WaterAllocationBasis (
	Name VARCHAR (250)  NOT NULL PRIMARY KEY,
	Term VARCHAR (250)  NOT NULL,
	Definition VARCHAR (5000)  NULL,
	Category VARCHAR (250)  NULL,
	SourceVocabularyURI	 VARCHAR (250)  NULL
);

CREATE TABLE CVs_WaterQualityIndicator (
	Name VARCHAR (250)  NOT NULL PRIMARY KEY,
	Term VARCHAR (250)  NOT NULL,
	Definition VARCHAR (5000)  NULL,
	Category VARCHAR (250)  NULL,
	SourceVocabularyURI	 VARCHAR (250)  NULL
);

CREATE TABLE CVs_WaterSourceType (
	Name VARCHAR (250)  NOT NULL PRIMARY KEY,
	Term VARCHAR (250)  NOT NULL,
	Definition VARCHAR (5000)  NULL,
	Category VARCHAR (250)  NULL,
	SourceVocabularyURI	 VARCHAR (250)  NULL
);

CREATE TABLE Date_dim (
	DateID INTEGER   NOT NULL PRIMARY KEY,
	Date DATE   NOT NULL,
	Year VARCHAR (4)  NULL
);

CREATE TABLE Methods_dim (
	MethodID INTEGER   NOT NULL PRIMARY KEY,
	MethodUUID VARCHAR (100)  NOT NULL,
	MethodName VARCHAR (50)  NOT NULL,
	MethodDescription TEXT   NOT NULL,
	MethodNEMILink VARCHAR (100)  NULL,
	ApplicableResourceTypeCV VARCHAR (100)  NOT NULL,
	MethodTypeCV VARCHAR (50)  NOT NULL,
	DataCoverageValue VARCHAR (100)  NULL,
	DataQualityValueCV VARCHAR (50)  NULL,
	DataConfidenceValue VARCHAR (50)  NULL
);

CREATE TABLE NHDMetadata (
	NHDMetadataID INTEGER   NOT NULL PRIMARY KEY,
	NHDNetworkStatusCV VARCHAR (50)  NOT NULL,
	NHDProductCV VARCHAR (50)  NULL,
	NHDUpdateDate DATE   NULL,
	NHDReachCode VARCHAR (50)  NULL,
	NHDMeasureNumber VARCHAR (50)  NULL
);

CREATE TABLE Organizations_dim (
	OrganizationID INTEGER   NOT NULL PRIMARY KEY,
	OrganizationUUID VARCHAR (250)  NOT NULL,
	OrganizationName VARCHAR (250)  NOT NULL,
	OrganizationPurview VARCHAR (250)  NULL,
	OrganizationWebsite VARCHAR (250)  NOT NULL,
	OrganizationPhoneNumber VARCHAR (250)  NOT NULL,
	OrganizationContactName VARCHAR (250)  NOT NULL,
	OrganizationContactEmail VARCHAR (250)  NOT NULL
);

CREATE TABLE RegulatoryOverlay_dim (
	RegulatoryOverlayID INTEGER   NOT NULL PRIMARY KEY,
	RegulatoryOverlayUUID VARCHAR (250)  NULL,
	RegulatoryOverlayNativeID VARCHAR (250)  NULL,
	RegulatoryName VARCHAR (50)  NOT NULL,
	RegulatoryDescription TEXT   NOT NULL,
	RegulatoryStatusCV VARCHAR (50)  NOT NULL,
	OversightAgency VARCHAR (250)  NOT NULL,
	RegulatoryStatute VARCHAR (500)  NULL,
	RegulatoryStatuteLink VARCHAR (500)  NULL,
	TimeframeStartID INTEGER   NOT NULL,
	TimeframeEndID INTEGER   NOT NULL,
	ReportYearTypeCV VARCHAR (10)  NOT NULL,
	ReportYearStartMonth VARCHAR (5)  NOT NULL,
	FOREIGN KEY (TimeframeEndID) REFERENCES Date_dim (DateID)
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY (TimeframeStartID) REFERENCES Date_dim (DateID)
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE RegulatoryReportingUnits_fact (
	BridgeID INTEGER   NOT NULL PRIMARY KEY,
	RegulatoryOverlayID INTEGER   NOT NULL,
	OrganizationID INTEGER   NOT NULL,
	ReportingUnitID INTEGER   NOT NULL,
	DataPublicationDateID INTEGER   NOT NULL,
	ReportYearCV VARCHAR (4)  NOT NULL,
	FOREIGN KEY (DataPublicationDateID) REFERENCES Date_dim (DateID)
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY (OrganizationID) REFERENCES Organizations_dim (OrganizationID)
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY (RegulatoryOverlayID) REFERENCES RegulatoryOverlay_dim (RegulatoryOverlayID)
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY (ReportingUnitID) REFERENCES ReportingUnits_dim (ReportingUnitID)
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE ReportingUnits_dim (
	ReportingUnitID INTEGER   NOT NULL PRIMARY KEY,
	ReportingUnitUUID VARCHAR (250)  NOT NULL,
	ReportingUnitNativeID VARCHAR (250)  NOT NULL,
	ReportingUnitName VARCHAR (250)  NOT NULL,
	ReportingUnitTypeCV VARCHAR (20)  NOT NULL,
	ReportingUnitUpdateDate DATE   NULL,
	ReportingUnitProductVersion VARCHAR (100)  NULL,
	StateCV VARCHAR (50)  NOT NULL,
	EPSGCodeCV VARCHAR (50)  NULL,
	Geometry BLOB   NULL
);

CREATE TABLE ReportYear_Dim (
	ReportYearId INTEGER   NOT NULL PRIMARY KEY,
	ReportYearCV VARCHAR (4)  NOT NULL
);

CREATE TABLE Sites_dim (
	SiteID INTEGER   NOT NULL PRIMARY KEY,
	SiteUUID VARCHAR (55)  NOT NULL,
	SiteNativeID VARCHAR (50)  NULL,
	SiteName VARCHAR (500)  NOT NULL,
	SiteTypeCV VARCHAR (100)  NULL,
	Longitude VARCHAR (50)  NOT NULL,
	Latitude VARCHAR (50)  NOT NULL,
	Geometry BLOB   NULL,
	CoordinateMethodCV VARCHAR (100)  NOT NULL,
	CoordinateAccuracy VARCHAR (255)  NULL,
	GNISCodeCV VARCHAR (50)  NULL,
	NHDMetadataID INTEGER   NULL,
	FOREIGN KEY (NHDMetadataID) REFERENCES NHDMetadata (NHDMetadataID)
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE SitesBridge_BeneficialUses_fact (
	SiteBridgeID INTEGER   NOT NULL PRIMARY KEY,
	BeneficialUseID INTEGER   NOT NULL,
	SiteVariableAmountID INTEGER   NOT NULL,
	FOREIGN KEY (BeneficialUseID) REFERENCES BeneficialUses_dim (BeneficialUseID)
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY (SiteVariableAmountID) REFERENCES SiteVariableAmounts_fact (SiteVariableAmountID)
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE SiteVariableAmounts_fact (
	SiteVariableAmountID INTEGER   NOT NULL PRIMARY KEY,
	OrganizationID INTEGER   NOT NULL,
	AllocationID INTEGER   NULL,
	SiteID INTEGER   NOT NULL,
	VariableSpecificID INTEGER   NOT NULL,
	BeneficialUseID INTEGER   NOT NULL,
	WaterSourceID INTEGER   NOT NULL,
	MethodID INTEGER   NOT NULL,
	TimeframeStart INTEGER   NOT NULL,
	TimeframeEnd INTEGER   NOT NULL,
	DataPublicationDate INTEGER   NOT NULL,
	ReportYear VARCHAR (4)  NULL,
	Amount FLOAT   NOT NULL,
	PopulationServed FLOAT   NULL,
	PowerGeneratedGWh FLOAT   NULL,
	IrrigatedAcreage FLOAT   NULL,
	IrrigationMethodCV VARCHAR (100)  NULL,
	CropTypeCV VARCHAR (100)  NULL,
	InterbasinTransferFromID VARCHAR (100)  NULL,
	InterbasinTransferToID VARCHAR (100)  NULL,
	Geometry BLOB   NULL,
	FOREIGN KEY (TimeframeEnd) REFERENCES Date_dim (DateID)
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY (DataPublicationDate) REFERENCES Date_dim (DateID)
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY (TimeframeStart) REFERENCES Date_dim (DateID)
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY (AllocationID) REFERENCES Allocations_dim (AllocationID)
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY (BeneficialUseID) REFERENCES BeneficialUses_dim (BeneficialUseID)
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY (ReportYear) REFERENCES CVs_ReportYearCV (Name)
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY (MethodID) REFERENCES Methods_dim (MethodID)
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY (OrganizationID) REFERENCES Organizations_dim (OrganizationID)
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY (SiteID) REFERENCES Sites_dim (SiteID)
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY (VariableSpecificID) REFERENCES Variables_dim (VariableSpecificID)
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY (WaterSourceID) REFERENCES WaterSources_dim (WaterSourceID)
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE USGSCategory_dim (
	USGSId INTEGER   NOT NULL PRIMARY KEY
);

CREATE TABLE Variables_dim (
	VariableSpecificID INTEGER   NOT NULL PRIMARY KEY,
	VariableSpecificUUID VARCHAR (250)  NULL,
	VariableSpecificCV VARCHAR (250)  NOT NULL,
	VariableCV VARCHAR (250)  NOT NULL,
	AggregationStatisticCV VARCHAR (50)  NOT NULL,
	AggregationInterval  NUMERIC (10)  NOT NULL,
	AggregationIntervalUnitCV  VARCHAR (50)  NOT NULL,
	ReportYearStartMonth  VARCHAR (10)  NOT NULL,
	ReportYearTypeCV  VARCHAR (10)  NOT NULL,
	AmountUnitCV VARCHAR (250)  NOT NULL,
	MaximumAmountUnitCV VARCHAR (255)  NULL
);

CREATE TABLE WaterSources_dim (
	WaterSourceID INTEGER   NOT NULL PRIMARY KEY,
	WaterSourceUUID VARCHAR (100)  NOT NULL,
	WaterSourceNativeID VARCHAR (250)  NULL,
	WaterSourceName VARCHAR (250)  NULL,
	WaterSourceTypeCV VARCHAR (100)  NOT NULL,
	WaterQualityIndicatorCV VARCHAR (100)  NOT NULL,
	GNISFeatureNameCV VARCHAR (250)  NULL,
	Geometry BLOB   NULL
);
