-- Adel Abdallah, Senior Hydroinformatics Specialist at the WSWC, Feb 2019

--This is a Data Definition Language (DDL) script that
--generates a blank schema of the Water Data Exchange Data Model (WaDE)
-- for Microsoft SQL Server database.

-- Generated by Adel Abdallah Feb, 2019 based on WaDE XML design named WaDE2.0_schema_star generated by DbWrench V4.04 @ http://www.dbwrench.com/
-- WaDE All rights reserved. See BSD 3-Clause Licence @ https://github.com/WSWCWaterDataExchange/WaDE2.0/blob/master/LICENSE 

--Open PostgreSQL, click on Databases>> Postgers>>   at the left Object Browser panel
--Simply copy all this script and paste into the new window of "SQL query"
--Then click execute. The script should run successfully and create the 40 empty tables of WaDE"

--Adel has commented this part because it is not used in WaDE so far 
--CREATE EXTENSION if not exists postgis;
--CREATE EXTENSION if not exists postgis_topology;
--CREATE EXTENSION if not exists fuzzystrmatch;
--CREATE EXTENSION if not exists postgis_tiger_geoCoder;
-------------------------------------------------------------------------------

drop schema if exists WaDE cascade;

create schema WaDE;

/***************************************************************************/
/*********************** CREATE WADE2.0_SCHEMA_STAR ************************/
/***************************************************************************/

create table WaDE.AggregatedAmounts (
	aggregatedamountid integer  NOT NULL primary key,
	aggregatedvariablemetadataid integer  NOT NULL,
	amountmetadataid integer  NOT NULL,
	variablespecificid integer  NOT NULL,
	watersourceid integer  NOT NULL,
	reportingunitid integer  NOT NULL,
	methodid integer  NOT NULL,
	timeid integer  NOT NULL,
	organizationid	 integer  NOT NULL,
	amount double precision  NOT NULL
);
create table WaDE.AggregatedVariableMetadata (
	aggregatedvariablemetadataid integer  NOT NULL primary key,
	amountunitcv varchar (100) NOT NULL,
	aggregationstatisticcv varchar (50) NOT NULL,
	aggregationinterval varchar (10) NOT NULL,
	aggregationintervalunitcv varchar (50) NOT NULL,
	reportyearstartmonth varchar (10) NOT NULL,
	reportyeartypecv varchar (50) NOT NULL
);
create table WaDE.AllocationAmounts (
	allocationamountid integer  NOT NULL primary key,
	allocationid integer  NOT NULL,
	siteid integer  NOT NULL,
	methodid integer  NOT NULL,
	timeid integer  NOT NULL,
	watersourceid integer  NOT NULL,
	sitevariablemetadataid integer  NOT NULL,
	variablespecificid integer  NOT NULL,
	organizationid	 integer  NOT NULL,
	amountmetadataid integer  NULL,
	allocationdutyamount double precision  NULL,
	allocationamount double precision  NOT NULL,
	allocationmaximum double precision  NULL
);
create table WaDE.Allocations (
	allocationid integer  NOT NULL primary key,
	nativeallocationid varchar (250) NULL,
	allocationuid varchar (50) NOT NULL,
	allocationowner varchar (255) NOT NULL,
	allocationapplicationdate date  NULL,
	allocationprioritydate date  NOT NULL,
	allocationlegalstatuscodecv bit (50) NOT NULL,
	allocationexpirationdate date  NULL,
	allocationchangeapplicationindicator varchar (100) NULL,
	legacyallocationids varchar (100) NULL,
	allocationbasiscv bigint  NULL,
	allocationacreage bigint  NULL
);
create table WaDE.AmountMetadata (
	amountmetadataid integer  NOT NULL primary key,
	beneficialusecategory varchar (255) NULL,
	primaryusecategory varchar (255) NULL,
	usgscategorycv varchar (255) NULL,
	sdwisidentifier varchar (255) NULL,
	naicscodecv varchar (255) NULL,
	populationserved double precision  NULL,
	irrigatedacreage double precision  NULL,
	irrigationmethod varchar (100) NULL,
	croptype varchar (100) NULL,
	powergeneratedgwh double precision  NULL,
	geometry bytea  NULL,
	interbasintransferfromid varchar (50) NULL,
	interbasintransfertoid varchar (255) NULL
);
create table WaDE.CVs_AggregationStatistic (
	name varchar (255) NOT NULL primary key,
	term varchar (255) NOT NULL,
	definition varchar (5000) NULL,
	category varchar (255) NULL,
	sourcevocabularyuri	 varchar (255) NULL
);
create table WaDE.CVs_EPSGCode (
	name varchar (255) NOT NULL primary key,
	term varchar (255) NOT NULL,
	definition varchar (5000) NULL,
	category varchar (255) NULL,
	sourcevocabularyuri	 varchar (255) NULL
);
create table WaDE.CVs_GNISCode (
	name varchar (255) NOT NULL primary key,
	term varchar (255) NOT NULL,
	definition varchar (5000) NULL,
	category varchar (255) NULL,
	sourcevocabularyuri	 varchar (255) NULL
);
create table WaDE.CVs_LegalStatusCode (
	name varchar (255) NOT NULL primary key,
	term varchar (255) NOT NULL,
	definition varchar (5000) NULL,
	category varchar (255) NULL,
	sourcevocabularyuri	 varchar (255) NULL
);
create table WaDE.CVs_MethodType (
	name varchar (255) NOT NULL primary key,
	term varchar (255) NOT NULL,
	definition varchar (5000) NULL,
	category varchar (255) NULL,
	sourcevocabularyuri	 varchar (255) NULL
);
create table WaDE.CVs_NAICSCode (
	name varchar (255) NOT NULL primary key,
	term varchar (255) NOT NULL,
	definition varchar (5000) NULL,
	category varchar (255) NULL,
	sourcevocabularyuri	 varchar (255) NULL
);
create table WaDE.CVs_NHDNetworkStatus (
	name varchar (255) NOT NULL primary key,
	term varchar (255) NOT NULL,
	definition varchar (5000) NULL,
	category varchar (255) NULL,
	sourcevocabularyuri	 varchar (255) NULL
);
create table WaDE.CVs_NHDProduct (
	name varchar (255) NOT NULL primary key,
	term varchar (255) NOT NULL,
	definition varchar (5000) NULL,
	category varchar (255) NULL,
	sourcevocabularyuri	 varchar (255) NULL
);
create table WaDE.CVs_RegulatoryStatus (
	name varchar (255) NOT NULL primary key,
	term varchar (255) NOT NULL,
	definition varchar (5000) NULL,
	category varchar (255) NULL,
	sourcevocabularyuri	 varchar (255) NULL
);
create table WaDE.CVs_ReportingUnitType (
	name varchar (255) NOT NULL primary key,
	term varchar (255) NOT NULL,
	definition varchar (5000) NULL,
	category varchar (255) NULL,
	sourcevocabularyuri	 varchar (255) NULL
);
create table WaDE.CVs_ReportYearCV (
	name varchar (255) NOT NULL primary key,
	term varchar (255) NOT NULL,
	definition varchar (5000) NULL,
	category varchar (255) NULL,
	sourcevocabularyuri	 varchar (255) NULL
);
create table WaDE.CVs_ReportYearType (
	name varchar (255) NOT NULL primary key,
	term varchar (255) NOT NULL,
	definition varchar (5000) NULL,
	category varchar (255) NULL,
	sourcevocabularyuri	 varchar (255) NULL
);
create table WaDE.CVs_Units (
	name varchar (255) NOT NULL primary key,
	term varchar (255) NOT NULL,
	definition varchar (5000) NULL,
	category varchar (255) NULL,
	sourcevocabularyuri	 varchar (255) NULL
);
create table WaDE.CVs_USGSCategory (
	name varchar (255) NOT NULL primary key,
	term varchar (255) NOT NULL,
	definition varchar (5000) NULL,
	category varchar (255) NULL,
	sourcevocabularyuri	 varchar (255) NULL
);
create table WaDE.CVs_Variable (
	name varchar (255) NOT NULL primary key,
	term varchar (255) NOT NULL,
	definition varchar (5000) NULL,
	category varchar (255) NULL,
	sourcevocabularyuri	 varchar (255) NULL
);
create table WaDE.CVs_VerticalDatumEPSGCode (
	name varchar (255) NOT NULL primary key,
	term varchar (255) NOT NULL,
	definition varchar (5000) NULL,
	category varchar (255) NULL,
	sourcevocabularyuri	 varchar (255) NULL
);
create table WaDE.CVs_WaterAllocationBasis (
	name varchar (255) NOT NULL primary key,
	term varchar (255) NOT NULL,
	definition varchar (5000) NULL,
	category varchar (255) NULL,
	sourcevocabularyuri	 varchar (255) NULL
);
create table WaDE.CVs_WaterAllocationBasis_dup (
	name varchar (255) NOT NULL primary key,
	term varchar (255) NOT NULL,
	definition varchar (5000) NULL,
	category varchar (255) NULL,
	sourcevocabularyuri	 varchar (255) NULL
);
create table WaDE.CVs_WaterQualityIndicator (
	name varchar (255) NOT NULL primary key,
	term varchar (255) NOT NULL,
	definition varchar (5000) NULL,
	category varchar (255) NULL,
	sourcevocabularyuri	 varchar (255) NULL
);
create table WaDE.CVs_WaterSourceType (
	name varchar (255) NOT NULL primary key,
	term varchar (255) NOT NULL,
	definition varchar (5000) NULL,
	category varchar (255) NULL,
	sourcevocabularyuri	 varchar (255) NULL
);
create table WaDE.Methods (
	methodid integer  NOT NULL primary key,
	methoduid varchar (100) NOT NULL,
	methodname varchar (50) NOT NULL,
	methoddescription text  NOT NULL,
	methodnemilink varchar (100) NULL,
	applicableresourcetypecv varchar (100) NOT NULL,
	methodtypecv varchar (50) NOT NULL,
	datacoveragevalue varchar (100) NULL,
	dataqualityvaluecv varchar (50) NULL,
	dataconfidencevalue varchar (50) NULL
);
create table WaDE.NHDMetadata (
	nhdmetadataid integer  NOT NULL primary key,
	nhdnetworkstatuscv varchar (50) NOT NULL,
	nhdproductcv varchar (50) NULL,
	nhdupdatedate date  NULL,
	nhdreachcode varchar (50) NULL,
	nhdmeasurenumber varchar (50) NULL
);
create table WaDE.Organizations (
	organizationid	 integer  NOT NULL primary key,
	organizationuid bit (255) NOT NULL,
	organizationname varchar (255) NOT NULL,
	organizationpurview varchar (255) NULL,
	organizationwebsite varchar (255) NULL,
	organizationphonenumber varchar (255) NULL,
	organizationcontactname varchar (255) NULL,
	organizationcontactemail varchar  NULL
);
create table WaDE.RegulatoryOverlay (
	regulatoryoverlayid integer  NOT NULL primary key,
	nativeregulatoryoverlayid varchar (255) NULL,
	regulatoryoverlayuid varchar (255) NULL,
	regulatoryname varchar (50) NOT NULL,
	regulatorydescription text  NOT NULL,
	regulatorystatuscv varchar (50) NOT NULL,
	oversightagency varchar (250) NOT NULL,
	regulatorystatute varchar (500) NULL,
	regulatorystatutelink varchar (500) NULL,
	timeframestart date  NOT NULL,
	timeframeend date  NOT NULL,
	reportyeartypecv varchar (10) NOT NULL,
	reportyearstartmonth varchar (5) NOT NULL
);
create table WaDE.RegulatoryReportingUnits (
	bridgeid integer  NOT NULL primary key,
	regulatoryoverlayid integer  NOT NULL,
	reportingunitid integer  NOT NULL,
	organizationid	 integer  NOT NULL,
	reportyearcv varchar (4) NULL,
	datapublicationdate date  NOT NULL
);
create table WaDE.ReportingUnits (
	reportingunitid integer  NOT NULL primary key,
	reportingunitnativeid varchar (250) NULL,
	reportingunituid varchar (255) NOT NULL,
	reportingunitname varchar (255) NOT NULL,
	reportingunittypecv varchar (20) NOT NULL,
	reportingunitupdatedate date  NULL,
	reportingunitproductversion varchar (100) NULL,
	statecv varchar (50) NOT NULL,
	epsgcodecv bit (50) NULL,
	verticaldatumepsgcodecv varchar (50) NULL,
	geometry bytea  NULL
);
create table WaDE.Sites (
	siteid integer  NOT NULL primary key,
	siteuid varchar (55) NOT NULL,
	nativesiteid varchar (50) NULL,
	sitename varchar (500) NOT NULL,
	sitetypecv varchar (100) NULL,
	longitude varchar (50) NOT NULL,
	latitude varchar (50) NOT NULL,
	geometry bytea  NULL,
	verticaldatumepsgcodecv varchar (50) NOT NULL,
	coordinatemethodcv varchar (100) NOT NULL,
	coordinateaccuracy varchar (255) NULL,
	gniscodecv varchar (50) NULL,
	nhdmetadataid integer  NULL
);
create table WaDE.SiteVariableAmounts (
	sitevariableamountid integer  NOT NULL primary key,
	allocationid integer  NOT NULL,
	timeid integer  NOT NULL,
	siteid integer  NOT NULL,
	methodid integer  NOT NULL,
	watersourceid integer  NOT NULL,
	sitevariablemetadataid integer  NOT NULL,
	variablespecificid integer  NOT NULL,
	organizationid	 integer  NOT NULL,
	amountmetadataid integer  NULL,
	amount double precision  NOT NULL
);
create table WaDE.SiteVariableMetadata (
	sitevariablemetadataid integer  NOT NULL primary key,
	sitevariablemetadatauid varchar (500) NULL,
	amountunitcv varchar (100) NOT NULL,
	aggregationstatisticcv varchar (50) NOT NULL,
	aggregationinterval varchar (5) NOT NULL,
	aggregationintervalunitcv varchar (50) NOT NULL,
	reportyearstartmonth varchar (5) NULL,
	reportyeartypecv varchar (50) NULL,
	maximumamountunitcv varchar (255) NULL
);
create table WaDE.Time_dim (
	timeid integer  NOT NULL primary key,
	reportyearcv varchar (4) NULL,
	timeframestart date  NULL,
	timeframeend date  NULL,
	datapublicationdate date  NULL
);
create table WaDE.Variables (
	variablespecificid integer  NOT NULL primary key,
	variablespecificuid varchar (255) NULL,
	variablespecificcv varchar (255) NOT NULL,
	variablecv varchar (255) NOT NULL,
	aggregationstatisticcv varchar (50) NULL,
	aggregationinterval  numeric (10) NULL,
	aggregationintervalunitcv  varchar (50) NULL,
	reportyearstartmonth  varchar (10) NULL,
	reportyeartypecv  varchar (10) NULL,
	amountunitcv varchar (10) NULL,
	maximumamountunitcv numeric (10) NULL
);
create table WaDE.WaterSources (
	watersourceid integer  NOT NULL primary key,
	watersourceuid varchar (100) NOT NULL,
	watersourcenativeid varchar (255) NULL,
	watersourcename varchar (255) NULL,
	watersourcetypecv varchar (100) NOT NULL,
	waterqualityindicatorcv varchar (100) NOT NULL,
	geometry bytea  NULL,
	gnisfeaturenamecv varchar (255) NULL
);

alter table WaDE.AggregatedAmounts add constraint fk_AggregatedAmounts_AggregatedVariableMetadata
foreign key (AggregatedVariableMetadataID) References WaDE.AggregatedVariableMetadata (AggregatedVariableMetadataID)
on update no Action on delete cascade;

alter table WaDE.AggregatedAmounts add constraint fk_AggregatedAmounts_AmountsMetadata
foreign key (AmountMetadataID) References WaDE.AmountMetadata (AmountMetadataID)
on update no Action on delete cascade;

alter table WaDE.AggregatedAmounts add constraint fk_AggregatedAmounts_Methods
foreign key (MethodID) References WaDE.Methods (MethodID)
on update no Action on delete cascade;

alter table WaDE.AggregatedAmounts add constraint fk_AggregatedAmounts_Organizations
foreign key (OrganizationID	) References WaDE.Organizations (OrganizationID	)
on update no Action on delete cascade;

alter table WaDE.AggregatedAmounts add constraint fk_AggregatedAmounts_ReportingUnits
foreign key (ReportingUnitID) References WaDE.ReportingUnits (ReportingUnitID)
on update no Action on delete cascade;

alter table WaDE.AggregatedAmounts add constraint fk_AggregatedAmounts_Time_dim
foreign key (TimeID) References WaDE.Time_dim (TimeID)
on update no Action on delete cascade;

alter table WaDE.AggregatedAmounts add constraint fk_AggregatedAmounts_VariablesSpecific
foreign key (VariableSpecificID) References WaDE.Variables (VariableSpecificID)
on update no Action on delete cascade;

alter table WaDE.AggregatedAmounts add constraint fk_AggregatedAmounts_WaterSources
foreign key (WaterSourceID) References WaDE.WaterSources (WaterSourceID)
on update no Action on delete cascade;

alter table WaDE.AllocationAmounts add constraint fk_WaterAllocationAmounts_AmountMetadata
foreign key (AmountMetadataID) References WaDE.AmountMetadata (AmountMetadataID)
on update no Action on delete cascade;

alter table WaDE.AllocationAmounts add constraint fk_WaterAllocationAmounts_Methods
foreign key (MethodID) References WaDE.Methods (MethodID)
on update no Action on delete cascade;

alter table WaDE.AllocationAmounts add constraint fk_WaterAllocationAmounts_Organizations
foreign key (OrganizationID	) References WaDE.Organizations (OrganizationID	)
on update no Action on delete cascade;

alter table WaDE.AllocationAmounts add constraint fk_WaterAllocationAmounts_Sites
foreign key (SiteID) References WaDE.Sites (SiteID)
on update no Action on delete cascade;

alter table WaDE.AllocationAmounts add constraint fk_WaterAllocationAmounts_SiteVariableMetadata
foreign key (SiteVariableMetadataID) References WaDE.SiteVariableMetadata (SiteVariableMetadataID)
on update no Action on delete cascade;

alter table WaDE.AllocationAmounts add constraint fk_WaterAllocationAmounts_Time_dim
foreign key (TimeID) References WaDE.Time_dim (TimeID)
on update no Action on delete cascade;

alter table WaDE.AllocationAmounts add constraint fk_WaterAllocationAmounts_VariablesSpecific
foreign key (VariableSpecificID) References WaDE.Variables (VariableSpecificID)
on update no Action on delete cascade;

alter table WaDE.AllocationAmounts add constraint fk_WaterAllocationAmounts_WaterAllocations
foreign key (AllocationID) References WaDE.Allocations (AllocationID)
on update no Action on delete cascade;

alter table WaDE.AllocationAmounts add constraint fk_WaterAllocationAmounts_WaterSources
foreign key (WaterSourceID) References WaDE.WaterSources (WaterSourceID)
on update no Action on delete cascade;

alter table WaDE.RegulatoryReportingUnits add constraint fk_RegulatoryReportingUnits_Organizations
foreign key (OrganizationID	) References WaDE.Organizations (OrganizationID	)
on update no Action on delete cascade;

alter table WaDE.RegulatoryReportingUnits add constraint fk_RegulatoryReportingUnits_RegulatoryOverlay
foreign key (RegulatoryOverlayID) References WaDE.RegulatoryOverlay (RegulatoryOverlayID)
on update no Action on delete cascade;

alter table WaDE.RegulatoryReportingUnits add constraint fk_RegulatoryReportingUnits_ReportingUnits
foreign key (ReportingUnitID) References WaDE.ReportingUnits (ReportingUnitID)
on update no Action on delete cascade;

alter table WaDE.Sites add constraint fk_Sites_NHDMetadata
foreign key (NHDMetadataID) References WaDE.NHDMetadata (NHDMetadataID)
on update no Action on delete cascade;

alter table WaDE.SiteVariableAmounts add constraint fk_SiteVariableAmounts_AmountMetadata
foreign key (AmountMetadataID) References WaDE.AmountMetadata (AmountMetadataID)
on update no Action on delete cascade;

alter table WaDE.SiteVariableAmounts add constraint fk_SiteVariableAmounts_Methods
foreign key (MethodID) References WaDE.Methods (MethodID)
on update no Action on delete cascade;

alter table WaDE.SiteVariableAmounts add constraint fk_SiteVariableAmounts_Organizations
foreign key (OrganizationID	) References WaDE.Organizations (OrganizationID	)
on update no Action on delete cascade;

alter table WaDE.SiteVariableAmounts add constraint fk_SiteVariableAmounts_Sites
foreign key (SiteID) References WaDE.Sites (SiteID)
on update no Action on delete cascade;

alter table WaDE.SiteVariableAmounts add constraint fk_SiteVariableAmounts_SiteVariableMetadata
foreign key (SiteVariableMetadataID) References WaDE.SiteVariableMetadata (SiteVariableMetadataID)
on update no Action on delete cascade;

alter table WaDE.SiteVariableAmounts add constraint fk_SiteVariableAmounts_Time_dim
foreign key (TimeID) References WaDE.Time_dim (TimeID)
on update no Action on delete cascade;

alter table WaDE.SiteVariableAmounts add constraint fk_SiteVariableAmounts_VariablesSpecific
foreign key (VariableSpecificID) References WaDE.Variables (VariableSpecificID)
on update no Action on delete cascade;

alter table WaDE.SiteVariableAmounts add constraint fk_SiteVariableAmounts_WaterAllocations
foreign key (AllocationID) References WaDE.Allocations (AllocationID)
on update no Action on delete cascade;

alter table WaDE.SiteVariableAmounts add constraint fk_SiteVariableAmounts_WaterSources
foreign key (WaterSourceID) References WaDE.WaterSources (WaterSourceID)
on update no Action on delete cascade;