-- Adel Abdallah, Senior Hydroinformatics Specialist at the WSWC, Feb 2019

--This is a Data Definition Language (DDL) script that
--generates a blank schema of the Water Data Exchange Data Model (WaDE)
-- for Microsoft SQL Server database.

-- Generated by Adel Abdallah Feb, 2019 based on WaDE XML design named WaDE2.0_schema_star generated by DbWrench V4.04 @ http://www.dbwrench.com/
-- WaDE All rights reserved. See BSD 3-Clause Licence @ https://github.com/WSWCWaterDataExchange/WaDE2.0/blob/master/LICENSE 

--Open PostgreSQL, click on Databases>> Postgers>>   at the left Object Browser panel
--Simply copy all this script and paste into the new window of "SQL query"
--Then click execute. The script should run successfully and create the 40 empty tables of WaDE"

--Adel has commented this part because it is not used in WaDE so far 
--CREATE EXTENSION if not exists postgis;
--CREATE EXTENSION if not exists postgis_topology;
--CREATE EXTENSION if not exists fuzzystrmatch;
--CREATE EXTENSION if not exists postgis_tiger_geoCoder;
-------------------------------------------------------------------------------

drop schema if exists WaDE cascade;

create schema WaDE;

/***************************************************************************/
/*********************** CREATE WADE2.0_SCHEMA_STAR ************************/
/***************************************************************************/

create table AggregatedAmounts_fact (
	aggregatedamountid integer  NOT NULL primary key,
	organizationid integer  NOT NULL,
	reportingunitid integer  NOT NULL,
	variablespecificid integer  NOT NULL,
	watersourceid integer  NOT NULL,
	methodid integer  NOT NULL,
	beneficialusesid integer  NOT NULL,
	timeframestart integer  NULL,
	timeframeend integer  NULL,
	datapublicationdate integer  NULL,
	amount double precision  NOT NULL,
	populationserved double precision  NULL,
	powergeneratedgwh double precision  NULL,
	irrigatedacreage double precision  NULL,
	interbasintransfertoid varchar (100) NULL,
	interbasintransferfromid varchar (100) NULL
);
create table AllocationAmounts_fact (
	allocationamountid integer  NOT NULL primary key,
	organizationid integer  NOT NULL,
	allocationid integer  NOT NULL,
	siteid integer  NOT NULL,
	variablespecificid integer  NOT NULL,
	watersourceid integer  NOT NULL,
	methodid integer  NOT NULL,
	beneficialusesid integer  NOT NULL,
	timeframestart integer  NOT NULL,
	timeframeend integer  NOT NULL,
	datapublicationdate integer  NOT NULL,
	allocationcropdutyamount double precision  NULL,
	allocationamount double precision  NULL,
	allocationmaximum double precision  NULL,
	populationserved double precision  NULL,
	powergeneratedgwh double precision  NULL,
	irrigatedacreage double precision  NULL,
	allocationcommunitywatersupplysystem varchar (250) NULL,
	sdwisidentifier varchar (250) NULL,
	interbasintransferfromid varchar (250) NULL,
	interbasintransfertoid varchar (250) NULL,
	geometry bytea  NULL
);
create table Allocations_dim (
	allocationid integer  NOT NULL primary key,
	allocationuid varchar (50) NOT NULL,
	allocationnativeid varchar (250) NOT NULL,
	allocationowner varchar (255) NOT NULL,
	allocationbasiscv varchar (250) NULL,
	allocationlegalstatuscv varchar (50) NOT NULL,
	allocationapplicationdate integer  NULL,
	allocationprioritydate integer  NOT NULL,
	allocationexpirationdate integer  NULL,
	allocationchangeapplicationindicator varchar (100) NULL,
	legacyallocationids varchar (100) NULL
);
create table BeneficialUses_dim (
	beneficialusesid integer  NOT NULL primary key,
	beneficialusecategory varchar (500) NOT NULL,
	primaryusecategory varchar (250) NULL,
	usgscategorycv varchar (250) NULL,
	naicscodecv varchar (250) NULL
);
create table CVs_AggregationStatistic (
	name varchar (250) NOT NULL primary key,
	term varchar (250) NOT NULL,
	definition varchar (5000) NULL,
	category varchar (250) NULL,
	sourcevocabularyuri	 varchar (250) NULL
);
create table CVs_CropType (
	name varchar (250) NOT NULL primary key,
	term varchar (250) NULL,
	definition varchar (5000) NULL,
	category varchar (250) NULL,
	sourcevocabularyuri varchar (250) NULL
);
create table CVs_EPSGCode (
	name varchar (250) NOT NULL primary key,
	term varchar (250) NOT NULL,
	definition varchar (5000) NULL,
	category varchar (250) NULL,
	sourcevocabularyuri	 varchar (250) NULL
);
create table CVs_GNISFeatureName (
	name varchar (250) NOT NULL primary key,
	term varchar (250) NOT NULL,
	definition varchar (5000) NULL,
	category varchar (250) NULL,
	sourcevocabularyuri	 varchar (250) NULL
);
create table CVs_IrrigationMethod (
	name varchar (250) NOT NULL primary key,
	term varchar (250) NULL,
	definition varchar (5000) NULL,
	category varchar (250) NULL,
	sourcevocabularyuri varchar (250) NULL
);
create table CVs_LegalStatus (
	name varchar (250) NOT NULL primary key,
	term varchar (250) NOT NULL,
	definition varchar (5000) NULL,
	category varchar (250) NULL,
	sourcevocabularyuri	 varchar (250) NULL
);
create table CVs_MethodType (
	name varchar (250) NOT NULL primary key,
	term varchar (250) NOT NULL,
	definition varchar (5000) NULL,
	category varchar (250) NULL,
	sourcevocabularyuri	 varchar (250) NULL
);
create table CVs_NAICSCode (
	name varchar (250) NOT NULL primary key,
	term varchar (250) NOT NULL,
	definition varchar (5000) NULL,
	category varchar (250) NULL,
	sourcevocabularyuri	 varchar (250) NULL
);
create table CVs_NHDNetworkStatus (
	name varchar (250) NOT NULL primary key,
	term varchar (250) NOT NULL,
	definition varchar (5000) NULL,
	category varchar (250) NULL,
	sourcevocabularyuri	 varchar (250) NULL
);
create table CVs_NHDProduct (
	name varchar (250) NOT NULL primary key,
	term varchar (250) NOT NULL,
	definition varchar (5000) NULL,
	category varchar (250) NULL,
	sourcevocabularyuri	 varchar (250) NULL
);
create table CVs_RegulatoryStatus (
	name varchar (250) NOT NULL primary key,
	term varchar (250) NOT NULL,
	definition varchar (5000) NULL,
	category varchar (250) NULL,
	sourcevocabularyuri	 varchar (250) NULL
);
create table CVs_ReportingUnitType (
	name varchar (250) NOT NULL primary key,
	term varchar (250) NOT NULL,
	definition varchar (5000) NULL,
	category varchar (250) NULL,
	sourcevocabularyuri	 varchar (250) NULL
);
create table CVs_ReportYearCV (
	name varchar (250) NOT NULL primary key,
	term varchar (250) NOT NULL,
	definition varchar (5000) NULL,
	category varchar (250) NULL,
	sourcevocabularyuri	 varchar (250) NULL
);
create table CVs_ReportYearType (
	name varchar (250) NOT NULL primary key,
	term varchar (250) NOT NULL,
	definition varchar (5000) NULL,
	category varchar (250) NULL,
	sourcevocabularyuri	 varchar (250) NULL
);
create table CVs_Units (
	name varchar (250) NOT NULL primary key,
	term varchar (250) NOT NULL,
	definition varchar (5000) NULL,
	category varchar (250) NULL,
	sourcevocabularyuri	 varchar (250) NULL
);
create table CVs_USGSCategory (
	name varchar (250) NOT NULL primary key,
	term varchar (250) NOT NULL,
	definition varchar (5000) NULL,
	category varchar (250) NULL,
	sourcevocabularyuri	 varchar (250) NULL
);
create table CVs_Variable (
	name varchar (250) NOT NULL primary key,
	term varchar (250) NOT NULL,
	definition varchar (5000) NULL,
	category varchar (250) NULL,
	sourcevocabularyuri	 varchar (250) NULL
);
create table CVs_VariableSpecific (
	name varchar (250) NOT NULL primary key,
	term varchar (250) NOT NULL,
	definition varchar (5000) NULL,
	category varchar (250) NULL,
	sourcevocabularyuri varchar (250) NULL
);
create table CVs_WaterAllocationBasis (
	name varchar (250) NOT NULL primary key,
	term varchar (250) NOT NULL,
	definition varchar (5000) NULL,
	category varchar (250) NULL,
	sourcevocabularyuri	 varchar (250) NULL
);
create table CVs_WaterQualityIndicator (
	name varchar (250) NOT NULL primary key,
	term varchar (250) NOT NULL,
	definition varchar (5000) NULL,
	category varchar (250) NULL,
	sourcevocabularyuri	 varchar (250) NULL
);
create table CVs_WaterSourceType (
	name varchar (250) NOT NULL primary key,
	term varchar (250) NOT NULL,
	definition varchar (5000) NULL,
	category varchar (250) NULL,
	sourcevocabularyuri	 varchar (250) NULL
);
create table Date_dim (
	dateid integer  NOT NULL primary key,
	reportyearcv varchar (4) NOT NULL,
	date date  NOT NULL
);
create table Methods_dim (
	methodid integer  NOT NULL primary key,
	methoduid varchar (100) NOT NULL,
	methodname varchar (50) NOT NULL,
	methoddescription text  NOT NULL,
	methodnemilink varchar (100) NULL,
	applicableresourcetypecv varchar (100) NOT NULL,
	methodtypecv varchar (50) NOT NULL,
	datacoveragevalue varchar (100) NULL,
	dataqualityvaluecv varchar (50) NULL,
	dataconfidencevalue varchar (50) NULL
);
create table NHDMetadata (
	nhdmetadataid integer  NOT NULL primary key,
	nhdnetworkstatuscv varchar (50) NOT NULL,
	nhdproductcv varchar (50) NULL,
	nhdupdatedate date  NULL,
	nhdreachcode varchar (50) NULL,
	nhdmeasurenumber varchar (50) NULL
);
create table Organizations_dim (
	organizationid integer  NOT NULL primary key,
	organizationuid varchar (250) NOT NULL,
	organizationname varchar (250) NOT NULL,
	organizationpurview varchar (250) NULL,
	organizationwebsite varchar (250) NOT NULL,
	organizationphonenumber varchar (250) NOT NULL,
	organizationcontactname varchar (250) NOT NULL,
	organizationcontactemail varchar (250) NOT NULL
);
create table RegulatoryOverlay_dim (
	regulatoryoverlayid integer  NOT NULL primary key,
	regulatoryoverlayuid varchar (250) NULL,
	regulatoryoverlaynativeid varchar (250) NULL,
	regulatoryname varchar (50) NOT NULL,
	regulatorydescription text  NOT NULL,
	regulatorystatuscv varchar (50) NOT NULL,
	oversightagency varchar (250) NOT NULL,
	regulatorystatute varchar (500) NULL,
	regulatorystatutelink varchar (500) NULL,
	timeframestart integer  NOT NULL,
	timeframeend integer  NOT NULL,
	reportyeartypecv varchar (10) NOT NULL,
	reportyearstartmonth varchar (5) NOT NULL
);
create table RegulatoryReportingUnits_fact (
	bridgeid integer  NOT NULL primary key,
	regulatoryoverlayid integer  NOT NULL,
	organizationid integer  NOT NULL,
	reportingunitid integer  NOT NULL,
	reportyearcv varchar (4) NULL,
	datapublicationdate integer  NOT NULL
);
create table ReportingUnits_dim (
	reportingunitid integer  NOT NULL primary key,
	reportingunituid varchar (250) NOT NULL,
	reportingunitnativeid varchar (250) NOT NULL,
	reportingunitname varchar (250) NOT NULL,
	reportingunittypecv varchar (20) NOT NULL,
	reportingunitupdatedate date  NULL,
	reportingunitproductversion varchar (100) NULL,
	statecv varchar (50) NOT NULL,
	epsgcodecv varchar (50) NULL,
	geometry bytea  NULL
);
create table Sites_dim (
	siteid integer  NOT NULL primary key,
	siteuid varchar (55) NOT NULL,
	sitenativeid varchar (50) NULL,
	sitename varchar (500) NOT NULL,
	sitetypecv varchar (100) NULL,
	longitude varchar (50) NOT NULL,
	latitude varchar (50) NOT NULL,
	geometry bytea  NULL,
	coordinatemethodcv varchar (100) NOT NULL,
	coordinateaccuracy varchar (255) NULL,
	gniscodecv varchar (50) NULL,
	nhdmetadataid integer  NULL
);
create table SiteVariableAmounts_fact (
	sitevariableamountid integer  NOT NULL primary key,
	organizationid integer  NOT NULL,
	allocationid integer  NULL,
	siteid integer  NOT NULL,
	variablespecificid integer  NOT NULL,
	watersourceid integer  NOT NULL,
	methodid integer  NOT NULL,
	beneficialusesid integer  NOT NULL,
	timeframestart integer  NOT NULL,
	timeframeend integer  NOT NULL,
	datapublicationdate integer  NOT NULL,
	amount double precision  NOT NULL,
	populationserved double precision  NULL,
	powergeneratedgwh double precision  NULL,
	irrigatedacreage double precision  NULL,
	irrigationmethodcv varchar (100) NULL,
	croptypecv varchar (100) NULL,
	interbasintransferfromid varchar (100) NULL,
	interbasintransfertoid varchar (100) NULL,
	geometry bytea  NULL
);
create table Variables_dim (
	variablespecificid integer  NOT NULL primary key,
	variablespecificuid varchar (250) NULL,
	variablespecificcv varchar (250) NOT NULL,
	variablecv varchar (250) NOT NULL,
	aggregationstatisticcv varchar (50) NOT NULL,
	aggregationinterval  numeric (10) NOT NULL,
	aggregationintervalunitcv  varchar (50) NOT NULL,
	reportyearstartmonth  varchar (10) NOT NULL,
	reportyeartypecv  varchar (10) NOT NULL,
	amountunitcv varchar (250) NOT NULL,
	maximumamountunitcv varchar (255) NULL
);
create table WaterSources_dim (
	watersourceid integer  NOT NULL primary key,
	watersourceuid varchar (100) NOT NULL,
	watersourcenativeid varchar (250) NULL,
	watersourcename varchar (250) NULL,
	watersourcetypecv varchar (100) NOT NULL,
	waterqualityindicatorcv varchar (100) NOT NULL,
	gnisfeaturenamecv varchar (250) NULL,
	geometry bytea  NULL
);

alter table AggregatedAmounts_fact add constraint fk_AggregatedAmounts_Date_dim_end
foreign key (TimeframeEnd) References Date_dim (DateID)
on update no Action on delete cascade;

alter table AggregatedAmounts_fact add constraint fk_AggregatedAmounts_Date_dim_end_pub
foreign key (DataPublicationDate) References Date_dim (DateID)
on update no Action on delete cascade;

alter table AggregatedAmounts_fact add constraint fk_AggregatedAmounts_Date_dim_start
foreign key (TimeframeStart) References Date_dim (DateID)
on update no Action on delete cascade;

alter table AggregatedAmounts_fact add constraint fk_AggregatedAmounts_fact_BeneficialUses_dim
foreign key (BeneficialUsesID) References BeneficialUses_dim (BeneficialUsesID)
on update no Action on delete cascade;

alter table AggregatedAmounts_fact add constraint fk_AggregatedAmounts_fact_Methods_dim
foreign key (MethodID) References Methods_dim (MethodID)
on update no Action on delete cascade;

alter table AggregatedAmounts_fact add constraint fk_AggregatedAmounts_fact_Organizations_dim
foreign key (OrganizationID) References Organizations_dim (OrganizationID)
on update no Action on delete cascade;

alter table AggregatedAmounts_fact add constraint fk_AggregatedAmounts_fact_ReportingUnits_dim
foreign key (ReportingUnitID) References ReportingUnits_dim (ReportingUnitID)
on update no Action on delete cascade;

alter table AggregatedAmounts_fact add constraint fk_AggregatedAmounts_fact_Variables_dim
foreign key (VariableSpecificID) References Variables_dim (VariableSpecificID)
on update no Action on delete cascade;

alter table AggregatedAmounts_fact add constraint fk_AggregatedAmounts_fact_WaterSources_dim
foreign key (WaterSourceID) References WaterSources_dim (WaterSourceID)
on update no Action on delete cascade;

alter table AllocationAmounts_fact add constraint fk_AllocationAmounts_fact_Allocations_dim
foreign key (AllocationID) References Allocations_dim (AllocationID)
on update no Action on delete cascade;

alter table AllocationAmounts_fact add constraint fk_AllocationAmounts_fact_BeneficialUses_dim
foreign key (BeneficialUsesID) References BeneficialUses_dim (BeneficialUsesID)
on update no Action on delete cascade;

alter table AllocationAmounts_fact add constraint fk_AllocationAmounts_fact_Date_dim_end
foreign key (TimeframeEnd) References Date_dim (DateID)
on update no Action on delete cascade;

alter table AllocationAmounts_fact add constraint fk_AllocationAmounts_fact_Date_dim_start
foreign key (TimeframeStart) References Date_dim (DateID)
on update no Action on delete cascade;

alter table AllocationAmounts_fact add constraint fk_AllocationAmounts_fact_Date_pub
foreign key (DataPublicationDate) References Date_dim (DateID)
on update no Action on delete cascade;

alter table AllocationAmounts_fact add constraint fk_AllocationAmounts_fact_Methods_dim
foreign key (MethodID) References Methods_dim (MethodID)
on update no Action on delete cascade;

alter table AllocationAmounts_fact add constraint fk_AllocationAmounts_fact_Organizations_dim
foreign key (OrganizationID) References Organizations_dim (OrganizationID)
on update no Action on delete cascade;

alter table AllocationAmounts_fact add constraint fk_AllocationAmounts_fact_Sites_dim
foreign key (SiteID) References Sites_dim (SiteID)
on update no Action on delete cascade;

alter table AllocationAmounts_fact add constraint fk_AllocationAmounts_fact_Variables_dim
foreign key (VariableSpecificID) References Variables_dim (VariableSpecificID)
on update no Action on delete cascade;

alter table AllocationAmounts_fact add constraint fk_AllocationAmounts_fact_WaterSources_dim
foreign key (WaterSourceID) References WaterSources_dim (WaterSourceID)
on update no Action on delete cascade;

alter table Allocations_dim add constraint fk_Allocations_dim_Date_dim_app
foreign key (AllocationApplicationDate) References Date_dim (DateID)
on update no Action on delete cascade;

alter table Allocations_dim add constraint fk_Allocations_dim_Date_dim_exp
foreign key (AllocationExpirationDate) References Date_dim (DateID)
on update no Action on delete cascade;

alter table Allocations_dim add constraint fk_Allocations_dim_Date_dim_prio
foreign key (AllocationPriorityDate) References Date_dim (DateID)
on update no Action on delete cascade;

alter table RegulatoryOverlay_dim add constraint fk_RegulatoryOverlay_dim_Date_dim_end
foreign key (TimeframeEnd) References Date_dim (DateID)
on update no Action on delete cascade;

alter table RegulatoryOverlay_dim add constraint fk_RegulatoryOverlay_dim_Date_dim_start
foreign key (TimeframeStart) References Date_dim (DateID)
on update no Action on delete cascade;

alter table RegulatoryReportingUnits_fact add constraint fk_RegulatoryReportingUnits_fact_Date_dim
foreign key (DataPublicationDate) References Date_dim (DateID)
on update no Action on delete cascade;

alter table RegulatoryReportingUnits_fact add constraint fk_RegulatoryReportingUnits_fact_Organizations_dim
foreign key (OrganizationID) References Organizations_dim (OrganizationID)
on update no Action on delete cascade;

alter table RegulatoryReportingUnits_fact add constraint fk_RegulatoryReportingUnits_fact_RegulatoryOverlay_dim
foreign key (RegulatoryOverlayID) References RegulatoryOverlay_dim (RegulatoryOverlayID)
on update no Action on delete cascade;

alter table RegulatoryReportingUnits_fact add constraint fk_RegulatoryReportingUnits_fact_ReportingUnits_dim
foreign key (ReportingUnitID) References ReportingUnits_dim (ReportingUnitID)
on update no Action on delete cascade;

alter table Sites_dim add constraint fk_Sites_NHDMetadata
foreign key (NHDMetadataID) References NHDMetadata (NHDMetadataID)
on update no Action on delete cascade;

alter table SiteVariableAmounts_fact add constraint fk_SiteVariableAmounts_Date_dim_end
foreign key (TimeframeEnd) References Date_dim (DateID)
on update no Action on delete cascade;

alter table SiteVariableAmounts_fact add constraint fk_SiteVariableAmounts_Date_dim_pub
foreign key (DataPublicationDate) References Date_dim (DateID)
on update no Action on delete cascade;

alter table SiteVariableAmounts_fact add constraint fk_SiteVariableAmounts_Date_dim_start
foreign key (TimeframeStart) References Date_dim (DateID)
on update no Action on delete cascade;

alter table SiteVariableAmounts_fact add constraint fk_SiteVariableAmounts_fact_Allocations_dim
foreign key (AllocationID) References Allocations_dim (AllocationID)
on update no Action on delete cascade;

alter table SiteVariableAmounts_fact add constraint fk_SiteVariableAmounts_fact_BeneficialUses_dim
foreign key (BeneficialUsesID) References BeneficialUses_dim (BeneficialUsesID)
on update no Action on delete cascade;

alter table SiteVariableAmounts_fact add constraint fk_SiteVariableAmounts_fact_Methods_dim
foreign key (MethodID) References Methods_dim (MethodID)
on update no Action on delete cascade;

alter table SiteVariableAmounts_fact add constraint fk_SiteVariableAmounts_fact_Organizations_dim
foreign key (OrganizationID) References Organizations_dim (OrganizationID)
on update no Action on delete cascade;

alter table SiteVariableAmounts_fact add constraint fk_SiteVariableAmounts_fact_Sites_dim
foreign key (SiteID) References Sites_dim (SiteID)
on update no Action on delete cascade;

alter table SiteVariableAmounts_fact add constraint fk_SiteVariableAmounts_fact_Variables_dim
foreign key (VariableSpecificID) References Variables_dim (VariableSpecificID)
on update no Action on delete cascade;

alter table SiteVariableAmounts_fact add constraint fk_SiteVariableAmounts_fact_WaterSources_dim
foreign key (WaterSourceID) References WaterSources_dim (WaterSourceID)
on update no Action on delete cascade;