-- Adel Abdallah, Senior Hydroinformatics Specialist at the WSWC, Feb 2019

--This is a Data Definition Language (DDL) script that
--generates a blank schema of the Water Data Exchange Data Model (WaDE)
-- for Microsoft SQL Server database.

-- Generated by Adel Abdallah Feb, 2019 based on WaDE XML design named WaDE2.0_schema_star generated by DbWrench V4.04 @ http://www.dbwrench.com/
-- WaDE All rights reserved. See BSD 3-Clause Licence @ https://github.com/WSWCWaterDataExchange/WaDE2.0/blob/master/LICENSE 

-- To create a blank WaDE database in SQL Server,
-- Open SQL Server, Click File >> New >> Query with Current Condition
-- Simply copy all this script and paste into the new window of "create query"
-- Then click "execute". The script should run successfully and create the xx empty tables of WaDE

----------------------------------------------------------------------------------------
-- Drop the database called 'WaDE' if it exists and then create a new database called 'WaDE'
USE master;
GO

IF DB_ID(N'WaDE') IS NOT NULL
DROP DATABASE WaDE;
GO

CREATE DATABASE WaDE;
GO

USE WaDE;
GO

CREATE SCHEMA WaDE;
GO

/***************************************************************************/
/*********************** CREATE WADE2.0_SCHEMA_STAR ************************/
/***************************************************************************/

CREATE TABLE AggBridge_BeneficialUses_fact (
	AggBridgeID int   NOT NULL,
	BeneficialUseID int   NOT NULL,
	AggregatedAmountID int   NOT NULL,
	PRIMARY KEY (AggBridgeID)
)
CREATE TABLE AggregatedAmounts_fact (
	AggregatedAmountID int   NOT NULL,
	OrganizationID int   NOT NULL,
	ReportingUnitID int   NOT NULL,
	VariableSpecificID int   NOT NULL,
	BeneficialUseID int   NOT NULL,
	WaterSourceID int   NOT NULL,
	MethodID int   NOT NULL,
	TimeframeStartID int   NULL,
	TimeframeEndID int   NULL,
	DataPublicationDate int   NULL,
	ReportYear varchar (4)  NULL,
	Amount float   NOT NULL,
	PopulationServed float   NULL,
	PowerGeneratedGWh float   NULL,
	IrrigatedAcreage float   NULL,
	InterbasinTransferToID varchar (100)  NULL,
	InterbasinTransferFromID varchar (100)  NULL,
	PRIMARY KEY (AggregatedAmountID)
)
CREATE TABLE AllocationAmounts_fact (
	AllocationAmountID int   NOT NULL,
	OrganizationID int   NOT NULL,
	AllocationID int   NOT NULL,
	SiteID int   NOT NULL,
	VariableSpecificID int   NOT NULL,
	BeneficialUsesID int   NOT NULL,
	WaterSourceID int   NOT NULL,
	MethodID int   NOT NULL,
	TimeframeStartDateID int   NOT NULL,
	TimeframeEndDateID int   NOT NULL,
	DataPublicationDateID int   NOT NULL,
	ReportYear varchar (4)  NOT NULL,
	AllocationCropDutyAmount float   NULL,
	AllocationAmount float   NULL,
	AllocationMaximum float   NULL,
	PopulationServed float   NULL,
	PowerGeneratedGWh float   NULL,
	IrrigatedAcreage float   NULL,
	AllocationCommunityWaterSupplySystem varchar (250)  NULL,
	SDWISIdentifier varchar (250)  NULL,
	InterbasinTransferFromID varchar (250)  NULL,
	InterbasinTransferToID varchar (250)  NULL,
	Geometry binary   NULL,
	PRIMARY KEY (AllocationAmountID)
)
CREATE TABLE AllocationBridge_BeneficialUses_fact (
	AllocationBridgeID int   NOT NULL,
	BeneficialUseID int   NOT NULL,
	AllocationAmountID int   NOT NULL,
	PRIMARY KEY (AllocationBridgeID)
)
CREATE TABLE Allocations_dim (
	AllocationID int   NOT NULL,
	AllocationUUID varchar (50)  NOT NULL,
	AllocationNativeID varchar (250)  NOT NULL,
	AllocationOwner varchar (255)  NOT NULL,
	AllocationBasisCV varchar (250)  NULL,
	AllocationLegalStatusCV varchar (50)  NOT NULL,
	AllocationApplicationDate int   NULL,
	AllocationPriorityDate int   NOT NULL,
	AllocationExpirationDate int   NULL,
	AllocationChangeApplicationIndicator varchar (100)  NULL,
	LegacyAllocationIDs varchar (100)  NULL,
	PRIMARY KEY (AllocationID)
)
CREATE TABLE BeneficialUses_dim (
	BeneficialUseID int   NOT NULL,
	BeneficialUseCategory varchar (500)  NOT NULL,
	PrimaryUseCategory varchar (250)  NULL,
	USGSCategoryNameCV varchar (250)  NULL,
	NAICSCodeNameCV varchar (250)  NULL,
	PRIMARY KEY (BeneficialUseID)
)
CREATE TABLE CVs_AggregationStatistic (
	Name varchar (250)  NOT NULL,
	Term varchar (250)  NOT NULL,
	Definition varchar (5000)  NULL,
	Category varchar (250)  NULL,
	SourceVocabularyURI	 varchar (250)  NULL,
	PRIMARY KEY (Name)
)
CREATE TABLE CVs_CropType (
	Name varchar (250)  NOT NULL,
	Term varchar (250)  NULL,
	Definition varchar (5000)  NULL,
	Category varchar (250)  NULL,
	SourceVocabularyURI varchar (250)  NULL,
	PRIMARY KEY (Name)
)
CREATE TABLE CVs_EPSGCode (
	Name varchar (250)  NOT NULL,
	Term varchar (250)  NOT NULL,
	Definition varchar (5000)  NULL,
	Category varchar (250)  NULL,
	SourceVocabularyURI	 varchar (250)  NULL,
	PRIMARY KEY (Name)
)
CREATE TABLE CVs_GNISFeatureName (
	Name varchar (250)  NOT NULL,
	Term varchar (250)  NOT NULL,
	Definition varchar (5000)  NULL,
	Category varchar (250)  NULL,
	SourceVocabularyURI	 varchar (250)  NULL,
	PRIMARY KEY (Name)
)
CREATE TABLE CVs_IrrigationMethod (
	Name varchar (250)  NOT NULL,
	Term varchar (250)  NULL,
	Definition varchar (5000)  NULL,
	Category varchar (250)  NULL,
	SourceVocabularyURI varchar (250)  NULL,
	PRIMARY KEY (Name)
)
CREATE TABLE CVs_LegalStatus (
	Name varchar (250)  NOT NULL,
	Term varchar (250)  NOT NULL,
	Definition varchar (5000)  NULL,
	Category varchar (250)  NULL,
	SourceVocabularyURI	 varchar (250)  NULL,
	PRIMARY KEY (Name)
)
CREATE TABLE CVs_MethodType (
	Name varchar (250)  NOT NULL,
	Term varchar (250)  NOT NULL,
	Definition varchar (5000)  NULL,
	Category varchar (250)  NULL,
	SourceVocabularyURI	 varchar (250)  NULL,
	PRIMARY KEY (Name)
)
CREATE TABLE CVs_NAICSCode (
	Name varchar (250)  NOT NULL,
	Term varchar (250)  NOT NULL,
	Definition varchar (5000)  NULL,
	Category varchar (250)  NULL,
	SourceVocabularyURI	 varchar (250)  NULL,
	PRIMARY KEY (Name)
)
CREATE TABLE CVs_NHDNetworkStatus (
	Name varchar (250)  NOT NULL,
	Term varchar (250)  NOT NULL,
	Definition varchar (5000)  NULL,
	Category varchar (250)  NULL,
	SourceVocabularyURI	 varchar (250)  NULL,
	PRIMARY KEY (Name)
)
CREATE TABLE CVs_NHDProduct (
	Name varchar (250)  NOT NULL,
	Term varchar (250)  NOT NULL,
	Definition varchar (5000)  NULL,
	Category varchar (250)  NULL,
	SourceVocabularyURI	 varchar (250)  NULL,
	PRIMARY KEY (Name)
)
CREATE TABLE CVs_RegulatoryStatus (
	Name varchar (250)  NOT NULL,
	Term varchar (250)  NOT NULL,
	Definition varchar (5000)  NULL,
	Category varchar (250)  NULL,
	SourceVocabularyURI	 varchar (250)  NULL,
	PRIMARY KEY (Name)
)
CREATE TABLE CVs_ReportingUnitType (
	Name varchar (250)  NOT NULL,
	Term varchar (250)  NOT NULL,
	Definition varchar (5000)  NULL,
	Category varchar (250)  NULL,
	SourceVocabularyURI	 varchar (250)  NULL,
	PRIMARY KEY (Name)
)
CREATE TABLE CVs_ReportYearCV (
	Name varchar (4)  NOT NULL,
	Term varchar (250)  NOT NULL,
	Definition varchar (5000)  NULL,
	Category varchar (250)  NULL,
	SourceVocabularyURI	 varchar (250)  NULL,
	PRIMARY KEY (Name)
)
CREATE TABLE CVs_ReportYearType (
	Name varchar (250)  NOT NULL,
	Term varchar (250)  NOT NULL,
	Definition varchar (5000)  NULL,
	Category varchar (250)  NULL,
	SourceVocabularyURI	 varchar (250)  NULL,
	PRIMARY KEY (Name)
)
CREATE TABLE CVs_Units (
	Name varchar (250)  NOT NULL,
	Term varchar (250)  NOT NULL,
	Definition varchar (5000)  NULL,
	Category varchar (250)  NULL,
	SourceVocabularyURI	 varchar (250)  NULL,
	PRIMARY KEY (Name)
)
CREATE TABLE CVs_USGSCategory (
	Name varchar (250)  NOT NULL,
	Term varchar (250)  NOT NULL,
	Definition varchar (5000)  NULL,
	Category varchar (250)  NULL,
	SourceVocabularyURI	 varchar (250)  NULL,
	PRIMARY KEY (Name)
)
CREATE TABLE CVs_Variable (
	Name varchar (250)  NOT NULL,
	Term varchar (250)  NOT NULL,
	Definition varchar (5000)  NULL,
	Category varchar (250)  NULL,
	SourceVocabularyURI	 varchar (250)  NULL,
	PRIMARY KEY (Name)
)
CREATE TABLE CVs_VariableSpecific (
	Name varchar (250)  NOT NULL,
	Term varchar (250)  NOT NULL,
	Definition varchar (5000)  NULL,
	Category varchar (250)  NULL,
	SourceVocabularyURI varchar (250)  NULL,
	PRIMARY KEY (Name)
)
CREATE TABLE CVs_WaterAllocationBasis (
	Name varchar (250)  NOT NULL,
	Term varchar (250)  NOT NULL,
	Definition varchar (5000)  NULL,
	Category varchar (250)  NULL,
	SourceVocabularyURI	 varchar (250)  NULL,
	PRIMARY KEY (Name)
)
CREATE TABLE CVs_WaterQualityIndicator (
	Name varchar (250)  NOT NULL,
	Term varchar (250)  NOT NULL,
	Definition varchar (5000)  NULL,
	Category varchar (250)  NULL,
	SourceVocabularyURI	 varchar (250)  NULL,
	PRIMARY KEY (Name)
)
CREATE TABLE CVs_WaterSourceType (
	Name varchar (250)  NOT NULL,
	Term varchar (250)  NOT NULL,
	Definition varchar (5000)  NULL,
	Category varchar (250)  NULL,
	SourceVocabularyURI	 varchar (250)  NULL,
	PRIMARY KEY (Name)
)
CREATE TABLE Date_dim (
	DateID int   NOT NULL,
	Date date   NOT NULL,
	Year varchar (4)  NULL,
	PRIMARY KEY (DateID)
)
CREATE TABLE Methods_dim (
	MethodID int   NOT NULL,
	MethodUUID varchar (100)  NOT NULL,
	MethodName varchar (50)  NOT NULL,
	MethodDescription text   NOT NULL,
	MethodNEMILink varchar (100)  NULL,
	ApplicableResourceTypeCV varchar (100)  NOT NULL,
	MethodTypeCV varchar (50)  NOT NULL,
	DataCoverageValue varchar (100)  NULL,
	DataQualityValueCV varchar (50)  NULL,
	DataConfidenceValue varchar (50)  NULL,
	PRIMARY KEY (MethodID)
)
CREATE TABLE NHDMetadata (
	NHDMetadataID int   NOT NULL,
	NHDNetworkStatusCV varchar (50)  NOT NULL,
	NHDProductCV varchar (50)  NULL,
	NHDUpdateDate date   NULL,
	NHDReachCode varchar (50)  NULL,
	NHDMeasureNumber varchar (50)  NULL,
	PRIMARY KEY (NHDMetadataID)
)
CREATE TABLE Organizations_dim (
	OrganizationID int   NOT NULL,
	OrganizationUUID varchar (250)  NOT NULL,
	OrganizationName varchar (250)  NOT NULL,
	OrganizationPurview varchar (250)  NULL,
	OrganizationWebsite varchar (250)  NOT NULL,
	OrganizationPhoneNumber varchar (250)  NOT NULL,
	OrganizationContactName varchar (250)  NOT NULL,
	OrganizationContactEmail varchar (250)  NOT NULL,
	PRIMARY KEY (OrganizationID)
)
CREATE TABLE RegulatoryOverlay_dim (
	RegulatoryOverlayID int   NOT NULL,
	RegulatoryOverlayUUID varchar (250)  NULL,
	RegulatoryOverlayNativeID varchar (250)  NULL,
	RegulatoryName varchar (50)  NOT NULL,
	RegulatoryDescription text   NOT NULL,
	RegulatoryStatusCV varchar (50)  NOT NULL,
	OversightAgency varchar (250)  NOT NULL,
	RegulatoryStatute varchar (500)  NULL,
	RegulatoryStatuteLink varchar (500)  NULL,
	TimeframeStartID int   NOT NULL,
	TimeframeEndID int   NOT NULL,
	ReportYearTypeCV varchar (10)  NOT NULL,
	ReportYearStartMonth varchar (5)  NOT NULL,
	PRIMARY KEY (RegulatoryOverlayID)
)
CREATE TABLE RegulatoryReportingUnits_fact (
	BridgeID int   NOT NULL,
	RegulatoryOverlayID int   NOT NULL,
	OrganizationID int   NOT NULL,
	ReportingUnitID int   NOT NULL,
	DataPublicationDateID int   NOT NULL,
	ReportYearCV varchar (4)  NOT NULL,
	PRIMARY KEY (BridgeID)
)
CREATE TABLE ReportingUnits_dim (
	ReportingUnitID int   NOT NULL,
	ReportingUnitUUID varchar (250)  NOT NULL,
	ReportingUnitNativeID varchar (250)  NOT NULL,
	ReportingUnitName varchar (250)  NOT NULL,
	ReportingUnitTypeCV varchar (20)  NOT NULL,
	ReportingUnitUpdateDate date   NULL,
	ReportingUnitProductVersion varchar (100)  NULL,
	StateCV varchar (50)  NOT NULL,
	EPSGCodeCV varchar (50)  NULL,
	Geometry binary   NULL,
	PRIMARY KEY (ReportingUnitID)
)
CREATE TABLE ReportYear_Dim (
	ReportYearId int   NOT NULL,
	ReportYearCV varchar (4)  NOT NULL,
	PRIMARY KEY (ReportYearId)
)
CREATE TABLE Sites_dim (
	SiteID int   NOT NULL,
	SiteUUID varchar (55)  NOT NULL,
	SiteNativeID varchar (50)  NULL,
	SiteName varchar (500)  NOT NULL,
	SiteTypeCV varchar (100)  NULL,
	Longitude varchar (50)  NOT NULL,
	Latitude varchar (50)  NOT NULL,
	Geometry binary   NULL,
	CoordinateMethodCV varchar (100)  NOT NULL,
	CoordinateAccuracy varchar (255)  NULL,
	GNISCodeCV varchar (50)  NULL,
	NHDMetadataID int   NULL,
	PRIMARY KEY (SiteID)
)
CREATE TABLE SitesBridge_BeneficialUses_fact (
	SiteBridgeID int   NOT NULL,
	BeneficialUseID int   NOT NULL,
	SiteVariableAmountID int   NOT NULL,
	PRIMARY KEY (SiteBridgeID)
)
CREATE TABLE SiteVariableAmounts_fact (
	SiteVariableAmountID int   NOT NULL,
	OrganizationID int   NOT NULL,
	AllocationID int   NULL,
	SiteID int   NOT NULL,
	VariableSpecificID int   NOT NULL,
	BeneficialUseID int   NOT NULL,
	WaterSourceID int   NOT NULL,
	MethodID int   NOT NULL,
	TimeframeStart int   NOT NULL,
	TimeframeEnd int   NOT NULL,
	DataPublicationDate int   NOT NULL,
	ReportYear varchar (4)  NULL,
	Amount float   NOT NULL,
	PopulationServed float   NULL,
	PowerGeneratedGWh float   NULL,
	IrrigatedAcreage float   NULL,
	IrrigationMethodCV varchar (100)  NULL,
	CropTypeCV varchar (100)  NULL,
	InterbasinTransferFromID varchar (100)  NULL,
	InterbasinTransferToID varchar (100)  NULL,
	Geometry binary   NULL,
	PRIMARY KEY (SiteVariableAmountID)
)
CREATE TABLE USGSCategory_dim (
	USGSId int   NOT NULL,
	PRIMARY KEY (USGSId)
)
CREATE TABLE Variables_dim (
	VariableSpecificID int   NOT NULL,
	VariableSpecificUUID varchar (250)  NULL,
	VariableSpecificCV varchar (250)  NOT NULL,
	VariableCV varchar (250)  NOT NULL,
	AggregationStatisticCV varchar (50)  NOT NULL,
	AggregationInterval  numeric (10)  NOT NULL,
	AggregationIntervalUnitCV  varchar (50)  NOT NULL,
	ReportYearStartMonth  varchar (10)  NOT NULL,
	ReportYearTypeCV  varchar (10)  NOT NULL,
	AmountUnitCV varchar (250)  NOT NULL,
	MaximumAmountUnitCV varchar (255)  NULL,
	PRIMARY KEY (VariableSpecificID)
)
CREATE TABLE WaterSources_dim (
	WaterSourceID int   NOT NULL,
	WaterSourceUUID varchar (100)  NOT NULL,
	WaterSourceNativeID varchar (250)  NULL,
	WaterSourceName varchar (250)  NULL,
	WaterSourceTypeCV varchar (100)  NOT NULL,
	WaterQualityIndicatorCV varchar (100)  NOT NULL,
	GNISFeatureNameCV varchar (250)  NULL,
	Geometry binary   NULL,
	PRIMARY KEY (WaterSourceID)
)

ALTER TABLE AggBridge_BeneficialUses_fact ADD CONSTRAINT fk_AggBridge_BeneficialUses_fact_AggregatedAmounts_fact
FOREIGN KEY (AggregatedAmountID) REFERENCES AggregatedAmounts_fact (AggregatedAmountID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE AggBridge_BeneficialUses_fact ADD CONSTRAINT fk_AggBridge_BeneficialUses_fact_BeneficialUses_dim
FOREIGN KEY (BeneficialUseID) REFERENCES BeneficialUses_dim (BeneficialUseID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE AggregatedAmounts_fact ADD CONSTRAINT fk_AggregatedAmounts_Date_dim_end
FOREIGN KEY (TimeframeEndID) REFERENCES Date_dim (DateID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE AggregatedAmounts_fact ADD CONSTRAINT fk_AggregatedAmounts_Date_dim_end_pub
FOREIGN KEY (DataPublicationDate) REFERENCES Date_dim (DateID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE AggregatedAmounts_fact ADD CONSTRAINT fk_AggregatedAmounts_Date_dim_start
FOREIGN KEY (TimeframeStartID) REFERENCES Date_dim (DateID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE AggregatedAmounts_fact ADD CONSTRAINT fk_AggregatedAmounts_fact_BeneficialUses_dim
FOREIGN KEY (BeneficialUseID) REFERENCES BeneficialUses_dim (BeneficialUseID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE AggregatedAmounts_fact ADD CONSTRAINT fk_AggregatedAmounts_fact_CVs_ReportYearCV
FOREIGN KEY (ReportYear) REFERENCES CVs_ReportYearCV (Name)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE AggregatedAmounts_fact ADD CONSTRAINT fk_AggregatedAmounts_fact_Methods_dim
FOREIGN KEY (MethodID) REFERENCES Methods_dim (MethodID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE AggregatedAmounts_fact ADD CONSTRAINT fk_AggregatedAmounts_fact_Organizations_dim
FOREIGN KEY (OrganizationID) REFERENCES Organizations_dim (OrganizationID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE AggregatedAmounts_fact ADD CONSTRAINT fk_AggregatedAmounts_fact_ReportingUnits_dim
FOREIGN KEY (ReportingUnitID) REFERENCES ReportingUnits_dim (ReportingUnitID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE AggregatedAmounts_fact ADD CONSTRAINT fk_AggregatedAmounts_fact_Variables_dim
FOREIGN KEY (VariableSpecificID) REFERENCES Variables_dim (VariableSpecificID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE AggregatedAmounts_fact ADD CONSTRAINT fk_AggregatedAmounts_fact_WaterSources_dim
FOREIGN KEY (WaterSourceID) REFERENCES WaterSources_dim (WaterSourceID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE AllocationAmounts_fact ADD CONSTRAINT fk_AllocationAmounts_fact_Allocations_dim
FOREIGN KEY (AllocationID) REFERENCES Allocations_dim (AllocationID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE AllocationAmounts_fact ADD CONSTRAINT fk_AllocationAmounts_fact_BeneficialUses_dim
FOREIGN KEY (BeneficialUsesID) REFERENCES BeneficialUses_dim (BeneficialUseID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE AllocationAmounts_fact ADD CONSTRAINT fk_AllocationAmounts_fact_CVs_ReportYearCV
FOREIGN KEY (ReportYear) REFERENCES CVs_ReportYearCV (Name)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE AllocationAmounts_fact ADD CONSTRAINT fk_AllocationAmounts_fact_Date_dim_end
FOREIGN KEY (TimeframeEndDateID) REFERENCES Date_dim (DateID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE AllocationAmounts_fact ADD CONSTRAINT fk_AllocationAmounts_fact_Date_dim_start
FOREIGN KEY (TimeframeStartDateID) REFERENCES Date_dim (DateID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE AllocationAmounts_fact ADD CONSTRAINT fk_AllocationAmounts_fact_Date_pub
FOREIGN KEY (DataPublicationDateID) REFERENCES Date_dim (DateID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE AllocationAmounts_fact ADD CONSTRAINT fk_AllocationAmounts_fact_Methods_dim
FOREIGN KEY (MethodID) REFERENCES Methods_dim (MethodID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE AllocationAmounts_fact ADD CONSTRAINT fk_AllocationAmounts_fact_Organizations_dim
FOREIGN KEY (OrganizationID) REFERENCES Organizations_dim (OrganizationID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE AllocationAmounts_fact ADD CONSTRAINT fk_AllocationAmounts_fact_Sites_dim
FOREIGN KEY (SiteID) REFERENCES Sites_dim (SiteID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE AllocationAmounts_fact ADD CONSTRAINT fk_AllocationAmounts_fact_Variables_dim
FOREIGN KEY (VariableSpecificID) REFERENCES Variables_dim (VariableSpecificID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE AllocationAmounts_fact ADD CONSTRAINT fk_AllocationAmounts_fact_WaterSources_dim
FOREIGN KEY (WaterSourceID) REFERENCES WaterSources_dim (WaterSourceID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE AllocationBridge_BeneficialUses_fact ADD CONSTRAINT fk_AllocationBridge_BeneficialUses_fact_AllocationAmounts_fact
FOREIGN KEY (AllocationAmountID) REFERENCES AllocationAmounts_fact (AllocationAmountID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE AllocationBridge_BeneficialUses_fact ADD CONSTRAINT fk_AllocationBridge_BeneficialUses_fact_BeneficialUses_dim
FOREIGN KEY (BeneficialUseID) REFERENCES BeneficialUses_dim (BeneficialUseID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE Allocations_dim ADD CONSTRAINT fk_Allocations_dim_Date_dim_app
FOREIGN KEY (AllocationApplicationDate) REFERENCES Date_dim (DateID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE Allocations_dim ADD CONSTRAINT fk_Allocations_dim_Date_dim_exp
FOREIGN KEY (AllocationExpirationDate) REFERENCES Date_dim (DateID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE Allocations_dim ADD CONSTRAINT fk_Allocations_dim_Date_dim_prio
FOREIGN KEY (AllocationPriorityDate) REFERENCES Date_dim (DateID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE BeneficialUses_dim ADD CONSTRAINT fk_BeneficialUses_dim_CVs_NAICSCode
FOREIGN KEY (NAICSCodeNameCV) REFERENCES CVs_NAICSCode (Name)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE BeneficialUses_dim ADD CONSTRAINT fk_BeneficialUses_dim_CVs_USGSCategory
FOREIGN KEY (USGSCategoryNameCV) REFERENCES CVs_USGSCategory (Name)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE RegulatoryOverlay_dim ADD CONSTRAINT fk_RegulatoryOverlay_dim_Date_dim_end
FOREIGN KEY (TimeframeEndID) REFERENCES Date_dim (DateID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE RegulatoryOverlay_dim ADD CONSTRAINT fk_RegulatoryOverlay_dim_Date_dim_start
FOREIGN KEY (TimeframeStartID) REFERENCES Date_dim (DateID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE RegulatoryReportingUnits_fact ADD CONSTRAINT fk_RegulatoryReportingUnits_fact_Date_dim
FOREIGN KEY (DataPublicationDateID) REFERENCES Date_dim (DateID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE RegulatoryReportingUnits_fact ADD CONSTRAINT fk_RegulatoryReportingUnits_fact_Organizations_dim
FOREIGN KEY (OrganizationID) REFERENCES Organizations_dim (OrganizationID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE RegulatoryReportingUnits_fact ADD CONSTRAINT fk_RegulatoryReportingUnits_fact_RegulatoryOverlay_dim
FOREIGN KEY (RegulatoryOverlayID) REFERENCES RegulatoryOverlay_dim (RegulatoryOverlayID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE RegulatoryReportingUnits_fact ADD CONSTRAINT fk_RegulatoryReportingUnits_fact_ReportingUnits_dim
FOREIGN KEY (ReportingUnitID) REFERENCES ReportingUnits_dim (ReportingUnitID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE Sites_dim ADD CONSTRAINT fk_Sites_NHDMetadata
FOREIGN KEY (NHDMetadataID) REFERENCES NHDMetadata (NHDMetadataID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE SitesBridge_BeneficialUses_fact ADD CONSTRAINT fk_SitesBridge_BeneficialUses_fact_BeneficialUses_dim
FOREIGN KEY (BeneficialUseID) REFERENCES BeneficialUses_dim (BeneficialUseID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE SitesBridge_BeneficialUses_fact ADD CONSTRAINT fk_SitesBridge_BeneficialUses_fact_SiteVariableAmounts_fact
FOREIGN KEY (SiteVariableAmountID) REFERENCES SiteVariableAmounts_fact (SiteVariableAmountID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE SiteVariableAmounts_fact ADD CONSTRAINT fk_SiteVariableAmounts_Date_dim_end
FOREIGN KEY (TimeframeEnd) REFERENCES Date_dim (DateID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE SiteVariableAmounts_fact ADD CONSTRAINT fk_SiteVariableAmounts_Date_dim_pub
FOREIGN KEY (DataPublicationDate) REFERENCES Date_dim (DateID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE SiteVariableAmounts_fact ADD CONSTRAINT fk_SiteVariableAmounts_Date_dim_start
FOREIGN KEY (TimeframeStart) REFERENCES Date_dim (DateID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE SiteVariableAmounts_fact ADD CONSTRAINT fk_SiteVariableAmounts_fact_Allocations_dim
FOREIGN KEY (AllocationID) REFERENCES Allocations_dim (AllocationID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE SiteVariableAmounts_fact ADD CONSTRAINT fk_SiteVariableAmounts_fact_BeneficialUses_dim
FOREIGN KEY (BeneficialUseID) REFERENCES BeneficialUses_dim (BeneficialUseID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE SiteVariableAmounts_fact ADD CONSTRAINT fk_SiteVariableAmounts_fact_CVs_ReportYearCV
FOREIGN KEY (ReportYear) REFERENCES CVs_ReportYearCV (Name)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE SiteVariableAmounts_fact ADD CONSTRAINT fk_SiteVariableAmounts_fact_Methods_dim
FOREIGN KEY (MethodID) REFERENCES Methods_dim (MethodID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE SiteVariableAmounts_fact ADD CONSTRAINT fk_SiteVariableAmounts_fact_Organizations_dim
FOREIGN KEY (OrganizationID) REFERENCES Organizations_dim (OrganizationID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE SiteVariableAmounts_fact ADD CONSTRAINT fk_SiteVariableAmounts_fact_Sites_dim
FOREIGN KEY (SiteID) REFERENCES Sites_dim (SiteID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE SiteVariableAmounts_fact ADD CONSTRAINT fk_SiteVariableAmounts_fact_Variables_dim
FOREIGN KEY (VariableSpecificID) REFERENCES Variables_dim (VariableSpecificID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE SiteVariableAmounts_fact ADD CONSTRAINT fk_SiteVariableAmounts_fact_WaterSources_dim
FOREIGN KEY (WaterSourceID) REFERENCES WaterSources_dim (WaterSourceID)
ON UPDATE NO ACTION ON DELETE NO ACTION