-- Adel Abdallah, Senior Hydroinformatics Specialist at the WSWC, Feb 2019

--This is a Data Definition Language (DDL) script that
--generates a blank schema of the Water Data Exchange Data Model (WaDE)
-- for Microsoft SQL Server database.

-- Generated by Adel Abdallah Feb, 2019 based on WaDE XML design named WaDE2.0_schema_star generated by DbWrench V4.04 @ http://www.dbwrench.com/
-- WaDE All rights reserved. See BSD 3-Clause Licence @ https://github.com/WSWCWaterDataExchange/WaDE2.0/blob/master/LICENSE 

-- To create a blank WaDE database in SQL Server,
-- Open SQL Server, Click File >> New >> Query with Current Condition
-- Simply copy all this script and paste into the new window of "create query"
-- Then click "execute". The script should run successfully and create the xx empty tables of WaDE

----------------------------------------------------------------------------------------
-- Drop the database called 'WaDE' if it exists and then create a new database called 'WaDE'
USE master;
GO

IF DB_ID(N'WaDE') IS NOT NULL
DROP DATABASE WaDE;
GO

CREATE DATABASE WaDE;
GO

USE WaDE;
GO

CREATE SCHEMA WaDE;
GO

/***************************************************************************/
/*************************** CREATE INPUTTABLES ****************************/
/***************************************************************************/

CREATE TABLE AggregatedAmounts_VariableTable (
	OrganizationUUID varchar (250)  NOT NULL,
	ReportingUnitNativeID varchar (250)  NOT NULL,
	VariableSpecificCV varchar (250)  NOT NULL,
	BeneficialUseCategory varchar (500)  NOT NULL,
	PrimaryUseCategory varchar (250)  NULL,
	AllocationUSGSCategoryCV varchar (250)  NULL,
	WaterSourceNativeID varchar (250)  NOT NULL,
	MethodName varchar (250)  NOT NULL,
	TimeframeStartDate date   NOT NULL,
	TimeframeEndDate date   NOT NULL,
	DataPublicationDate date   NOT NULL,
	ReportYear varchar (4)  NOT NULL,
	Amount float   NULL,
	PopulationServed float   NULL,
	PowerGeneratedGWh float   NULL,
	IrrigatedAcreage float   NULL,
	InterbasinTransferFromID varchar (250)  NULL,
	InterbasinTransferToID varchar (250)  NULL,
	PRIMARY KEY (OrganizationUUID)
)
CREATE TABLE AllocationAmounts_VariableTable (
	OrganizationUUID nvarchar (250)  NOT NULL,
	AllocationNativeID nvarchar (250)  NOT NULL,
	AllocationOwner nvarchar (250)  NOT NULL,
	AllocationBasisCV varchar (250)  NULL,
	AllocationLegalStatusCV nvarchar (250)  NOT NULL,
	AllocationApplicationDate date   NULL,
	AllocationPriorityDate date   NOT NULL,
	AllocationExpirationDate date   NULL,
	AllocationChangeApplicationIndicator nvarchar (250)  NULL,
	LegacyAllocationIDs nvarchar (250)  NULL,
	SiteNativeID nvarchar (250)  NOT NULL,
	VariableSpecificCV nvarchar (250)  NOT NULL,
	BeneficialUseCategory nvarchar (500)  NOT NULL,
	PrimaryUseCategory nvarchar (250)  NULL,
	AllocationUSGSCategoryCV nvarchar (250)  NULL,
	WaterSourceName nvarchar (250)  NOT NULL,
	MethodName nvarchar (250)  NOT NULL,
	TimeframeStartDate date   NOT NULL,
	TimeframeEndDate date   NOT NULL,
	DataPublicationDate date   NOT NULL,
	ReportYear nchar (4)  NOT NULL,
	AllocationCropDutyAmount float   NULL,
	AllocationAmount float   NULL,
	AllocationMaximum float   NULL,
	PopulationServed float   NULL,
	PowerGeneratedGWh float   NULL,
	IrrigatedAcreage float   NULL,
	AllocationCommunityWaterSupplySystem nvarchar (250)  NULL,
	SDWISIdentifier nvarchar (250)  NULL,
	Geometry geometry   NULL,
	PRIMARY KEY (OrganizationUUID)
)
CREATE TABLE BeneficialUses_dim_Input (
	BeneficialUseCategory nvarchar (500)  NOT NULL,
	PrimaryUseCategory nvarchar (250)  NULL,
	USGSCategoryNameCV nvarchar (250)  NULL,
	NAICSCodeNameCV nvarchar (250)  NULL,
	PRIMARY KEY (BeneficialUseCategory)
)
CREATE TABLE Methods_dim_input (
	MethodName nvarchar (50)  NOT NULL,
	MethodDescription text   NOT NULL,
	MethodNEMILink nvarchar (100)  NULL,
	ApplicableResourceTypeCV nvarchar (100)  NOT NULL,
	MethodTypeCV nvarchar (50)  NOT NULL,
	DataCoverageValue nvarchar (100)  NULL,
	DataQualityValueCV nvarchar (50)  NULL,
	DataConfidenceValue nvarchar (50)  NULL,
	PRIMARY KEY (MethodName)
)
CREATE TABLE Organizations_dim_Input (
	OrganizationUUID nvarchar (250)  NOT NULL,
	OrganizationName nvarchar (250)  NOT NULL,
	OrganizationPurview nvarchar (250)  NULL,
	OrganizationWebsite nvarchar (250)  NOT NULL,
	OrganizationPhoneNumber nvarchar (250)  NOT NULL,
	OrganizationContactName nvarchar (250)  NOT NULL,
	OrganizationContactEmail nvarchar (250)  NOT NULL,
	PRIMARY KEY (OrganizationUUID)
)
CREATE TABLE RegulatoryOverlay_dim_input (
	RegulatoryOverlayNativeID nvarchar (250)  NULL,
	RegulatoryName nvarchar (50)  NOT NULL,
	RegulatoryDescription nvarchar(max)   NOT NULL,
	RegulatoryStatusCV nvarchar (50)  NOT NULL,
	OversightAgency nvarchar (250)  NOT NULL,
	RegulatoryStatute nvarchar (500)  NULL,
	RegulatoryStatuteLink varchar (500)  NULL,
	TimeframeStartID bigint   NOT NULL,
	TimeframeEndID bigint   NOT NULL,
	ReportYearTypeCV nvarchar (10)  NOT NULL,
	ReportYearStartMonth nvarchar (5)  NOT NULL,
	PRIMARY KEY (RegulatoryOverlayNativeID)
)
CREATE TABLE RegulatoryReportingUnits_VariableTable (
	RegulatoryOverlayUUID varchar (250)  NOT NULL,
	OrganizationUUID varchar (250)  NOT NULL,
	ReportingUnitNativeID varchar (250)  NOT NULL,
	DataPublicationDate date   NOT NULL,
	ReportYearCV varchar (4)  NOT NULL,
	PRIMARY KEY (RegulatoryOverlayUUID)
)
CREATE TABLE ReportingUnits_dim_Input (
	ReportingUnitNativeID nvarchar (250)  NOT NULL,
	ReportingUnitName nvarchar (250)  NOT NULL,
	ReportingUnitTypeCV nvarchar (20)  NOT NULL,
	ReportingUnitUpdateDate date   NULL,
	ReportingUnitProductVersion nvarchar (100)  NULL,
	StateCV nvarchar (50)  NOT NULL,
	EPSGCodeCV nvarchar (50)  NULL,
	Geometry polygon   NULL,
	PRIMARY KEY (ReportingUnitNativeID)
)
CREATE TABLE Sites_dim_input (
	SiteNativeID nvarchar (50)  NULL,
	SiteName nvarchar (500)  NOT NULL,
	SiteTypeCV varchar (100)  NULL,
	Longitude nvarchar (50)  NOT NULL,
	Latitude nvarchar (50)  NOT NULL,
	Geometry geometry   NULL,
	CoordinateMethodCV nvarchar (100)  NOT NULL,
	CoordinateAccuracy nvarchar (255)  NULL,
	GNISCodeCV nvarchar (50)  NULL,
	PRIMARY KEY (SiteNativeID)
)
CREATE TABLE SiteVariableAmounts_VariableTable (
	OrganizationUUID varchar (250)  NOT NULL,
	AllocationUUID varchar (250)  NULL,
	SiteNativeID varchar (250)  NOT NULL,
	VariableSpecificCV varchar (250)  NOT NULL,
	BeneficialUseCategory varchar (500)  NOT NULL,
	PrimaryUseCategory varchar (250)  NULL,
	AllocationUSGSCategoryCV varchar (250)  NULL,
	WaterSourceNativeID varchar (250)  NOT NULL,
	MethodName varchar (250)  NOT NULL,
	TimeframeStartDate date   NOT NULL,
	TimeframeEndDate date   NOT NULL,
	DataPublicationDate date   NOT NULL,
	ReportYear varchar (4)  NOT NULL,
	Amount float   NULL,
	PopulationServed float   NULL,
	PowerGeneratedGWh float   NULL,
	IrrigatedAcreage float   NULL,
	AllocationCommunityWaterSupplySystem varchar (250)  NULL,
	SDWISIdentifier varchar (250)  NULL,
	InterbasinTransferFromID varchar (250)  NULL,
	InterbasinTransferToID varchar (250)  NULL,
	Geometry binary   NULL,
	PRIMARY KEY (OrganizationUUID)
)
CREATE TABLE Variables_dim_input (
	VariableSpecificCV nvarchar (250)  NOT NULL,
	VariableCV nvarchar (250)  NOT NULL,
	AggregationStatisticCV nvarchar (50)  NOT NULL,
	AggregationInterval  numeric (10)  NOT NULL,
	AggregationIntervalUnitCV  nvarchar (50)  NOT NULL,
	ReportYearStartMonth  nvarchar (10)  NOT NULL,
	ReportYearTypeCV  nvarchar (10)  NOT NULL,
	AmountUnitCV nvarchar (250)  NOT NULL,
	MaximumAmountUnitCV nvarchar (255)  NULL,
	PRIMARY KEY (VariableSpecificCV)
)
CREATE TABLE WaterSources_dim_input (
	WaterSourceNativeID nvarchar (250)  NULL,
	WaterSourceName nvarchar (250)  NULL,
	WaterSourceTypeCV nvarchar (100)  NOT NULL,
	WaterQualityIndicatorCV nvarchar (100)  NOT NULL,
	GNISFeatureNameCV nvarchar (250)  NULL,
	Geometry geometry   NULL,
	PRIMARY KEY (WaterSourceNativeID)
)
/***************************************************************************/
/**************************** CREATE WADE2_STAR ****************************/
/***************************************************************************/

CREATE TABLE AggBridge_BeneficialUses_fact (
	AggBridgeID bigint   NOT NULL,
	BeneficialUseID bigint   NOT NULL,
	AggregatedAmountID bigint   NOT NULL,
	PRIMARY KEY (AggBridgeID)
)
CREATE TABLE AggregatedAmounts_fact (
	AggregatedAmountID bigint   NOT NULL,
	OrganizationID bigint   NOT NULL,
	ReportingUnitID bigint   NOT NULL,
	VariableSpecificID bigint   NOT NULL,
	BeneficialUseID bigint   NOT NULL,
	WaterSourceID bigint   NOT NULL,
	MethodID bigint   NOT NULL,
	TimeframeStartID bigint   NULL,
	TimeframeEndID bigint   NULL,
	DataPublicationDate bigint   NULL,
	ReportYear nchar (4)  NULL,
	Amount float   NOT NULL,
	PopulationServed float   NULL,
	PowerGeneratedGWh float   NULL,
	IrrigatedAcreage float   NULL,
	InterbasinTransferToID nvarchar (100)  NULL,
	InterbasinTransferFromID nvarchar (100)  NULL,
	PRIMARY KEY (AggregatedAmountID)
)
CREATE TABLE AllocationAmounts_fact (
	AllocationAmountID bigint   NOT NULL,
	OrganizationID bigint   NOT NULL,
	AllocationID bigint   NOT NULL,
	SiteID bigint   NOT NULL,
	VariableSpecificID bigint   NOT NULL,
	BeneficialUsesID bigint   NOT NULL,
	WaterSourceID bigint   NOT NULL,
	MethodID bigint   NOT NULL,
	TimeframeStartDateID bigint   NOT NULL,
	TimeframeEndDateID bigint   NOT NULL,
	DataPublicationDateID bigint   NOT NULL,
	ReportYear nchar (4)  NOT NULL,
	AllocationCropDutyAmount float   NULL,
	AllocationAmount float   NULL,
	AllocationMaximum float   NULL,
	PopulationServed float   NULL,
	PowerGeneratedGWh float   NULL,
	IrrigatedAcreage float   NULL,
	AllocationCommunityWaterSupplySystem nvarchar (250)  NULL,
	SDWISIdentifier nvarchar (250)  NULL,
	Geometry geometry   NULL,
	PRIMARY KEY (AllocationAmountID)
)
CREATE TABLE AllocationBridge_BeneficialUses_fact (
	AllocationBridgeID bigint   NOT NULL,
	BeneficialUseID bigint   NOT NULL,
	AllocationAmountID bigint   NOT NULL,
	PRIMARY KEY (AllocationBridgeID)
)
CREATE TABLE Allocations_dim (
	AllocationID bigint   NOT NULL,
	AllocationUUID nvarchar (50)  NOT NULL,
	AllocationNativeID nvarchar (250)  NOT NULL,
	AllocationOwner nvarchar (255)  NOT NULL,
	AllocationBasisCV nvarchar (250)  NULL,
	AllocationLegalStatusCV nvarchar (50)  NOT NULL,
	AllocationApplicationDate bigint   NULL,
	AllocationPriorityDate bigint   NOT NULL,
	AllocationExpirationDate bigint   NULL,
	AllocationChangeApplicationIndicator nvarchar (100)  NULL,
	LegacyAllocationIDs nvarchar (100)  NULL,
	PRIMARY KEY (AllocationID)
)
CREATE TABLE Allocations_dim_Input (
	AllocationNativeID nvarchar (250)  NOT NULL,
	AllocationOwner nvarchar (255)  NOT NULL,
	AllocationBasisCV nvarchar (250)  NULL,
	AllocationLegalStatusCV nvarchar (50)  NOT NULL,
	AllocationApplicationDate bigint   NULL,
	AllocationPriorityDate bigint   NOT NULL,
	AllocationExpirationDate bigint   NULL,
	AllocationChangeApplicationIndicator nvarchar (100)  NULL,
	LegacyAllocationIDs nvarchar (100)  NULL,
	PRIMARY KEY (AllocationNativeID)
)
CREATE TABLE BeneficialUses_dim (
	BeneficialUseID bigint   NOT NULL,
	BeneficialUseUUID nvarchar (500)  NULL,
	BeneficialUseCategory nvarchar (500)  NOT NULL,
	PrimaryUseCategory nvarchar (250)  NULL,
	USGSCategoryNameCV nvarchar (250)  NULL,
	NAICSCodeNameCV nvarchar (250)  NULL,
	PRIMARY KEY (BeneficialUseID)
)
CREATE TABLE CVs_AggregationStatistic (
	Name varchar (250)  NOT NULL,
	Term varchar (250)  NOT NULL,
	Definition varchar (5000)  NULL,
	Category varchar (250)  NULL,
	SourceVocabularyURI	 varchar (250)  NULL,
	PRIMARY KEY (Name)
)
CREATE TABLE CVs_CropType (
	Name varchar (250)  NOT NULL,
	Term varchar (250)  NULL,
	Definition varchar (5000)  NULL,
	Category varchar (250)  NULL,
	SourceVocabularyURI varchar (250)  NULL,
	PRIMARY KEY (Name)
)
CREATE TABLE CVs_EPSGCode (
	Name varchar (250)  NOT NULL,
	Term varchar (250)  NOT NULL,
	Definition varchar (5000)  NULL,
	Category varchar (250)  NULL,
	SourceVocabularyURI	 varchar (250)  NULL,
	PRIMARY KEY (Name)
)
CREATE TABLE CVs_GNISFeatureName (
	Name varchar (250)  NOT NULL,
	Term varchar (250)  NOT NULL,
	Definition varchar (5000)  NULL,
	Category varchar (250)  NULL,
	SourceVocabularyURI	 varchar (250)  NULL,
	PRIMARY KEY (Name)
)
CREATE TABLE CVs_IrrigationMethod (
	Name varchar (250)  NOT NULL,
	Term varchar (250)  NULL,
	Definition varchar (5000)  NULL,
	Category varchar (250)  NULL,
	SourceVocabularyURI varchar (250)  NULL,
	PRIMARY KEY (Name)
)
CREATE TABLE CVs_LegalStatus (
	Name varchar (250)  NOT NULL,
	Term varchar (250)  NOT NULL,
	Definition varchar (5000)  NULL,
	Category varchar (250)  NULL,
	SourceVocabularyURI	 varchar (250)  NULL,
	PRIMARY KEY (Name)
)
CREATE TABLE CVs_MethodType (
	Name varchar (250)  NOT NULL,
	Term varchar (250)  NOT NULL,
	Definition varchar (5000)  NULL,
	Category varchar (250)  NULL,
	SourceVocabularyURI	 varchar (250)  NULL,
	PRIMARY KEY (Name)
)
CREATE TABLE CVs_NAICSCode (
	Name nvarchar (250)  NOT NULL,
	Term nvarchar (250)  NOT NULL,
	Definition nvarchar(max)   NULL,
	Category nvarchar (250)  NULL,
	SourceVocabularyURI	 nvarchar (250)  NULL,
	PRIMARY KEY (Name)
)
CREATE TABLE CVs_NHDNetworkStatus (
	Name varchar (250)  NOT NULL,
	Term varchar (250)  NOT NULL,
	Definition varchar (5000)  NULL,
	Category varchar (250)  NULL,
	SourceVocabularyURI	 varchar (250)  NULL,
	PRIMARY KEY (Name)
)
CREATE TABLE CVs_NHDProduct (
	Name varchar (250)  NOT NULL,
	Term varchar (250)  NOT NULL,
	Definition varchar (5000)  NULL,
	Category varchar (250)  NULL,
	SourceVocabularyURI	 varchar (250)  NULL,
	PRIMARY KEY (Name)
)
CREATE TABLE CVs_RegulatoryStatus (
	Name varchar (250)  NOT NULL,
	Term varchar (250)  NOT NULL,
	Definition varchar (5000)  NULL,
	Category varchar (250)  NULL,
	SourceVocabularyURI	 varchar (250)  NULL,
	PRIMARY KEY (Name)
)
CREATE TABLE CVs_ReportingUnitType (
	Name varchar (250)  NOT NULL,
	Term varchar (250)  NOT NULL,
	Definition varchar (5000)  NULL,
	Category varchar (250)  NULL,
	SourceVocabularyURI	 varchar (250)  NULL,
	PRIMARY KEY (Name)
)
CREATE TABLE CVs_ReportYearCV (
	Name nvarchar (4)  NOT NULL,
	Term nvarchar (250)  NOT NULL,
	Definition nvarchar(max)   NULL,
	Category nvarchar (250)  NULL,
	SourceVocabularyURI	 nvarchar (250)  NULL,
	PRIMARY KEY (Name)
)
CREATE TABLE CVs_ReportYearType (
	Name varchar (250)  NOT NULL,
	Term varchar (250)  NOT NULL,
	Definition varchar (5000)  NULL,
	Category varchar (250)  NULL,
	SourceVocabularyURI	 varchar (250)  NULL,
	PRIMARY KEY (Name)
)
CREATE TABLE CVs_Units (
	Name varchar (250)  NOT NULL,
	Term varchar (250)  NOT NULL,
	Definition varchar (5000)  NULL,
	Category varchar (250)  NULL,
	SourceVocabularyURI	 varchar (250)  NULL,
	PRIMARY KEY (Name)
)
CREATE TABLE CVs_USGSCategory (
	Name nvarchar (250)  NOT NULL,
	Term nvarchar (250)  NOT NULL,
	Definition nvarchar(max)   NULL,
	Category nvarchar (250)  NULL,
	SourceVocabularyURI	 nvarchar (250)  NULL,
	PRIMARY KEY (Name)
)
CREATE TABLE CVs_Variable (
	Name varchar (250)  NOT NULL,
	Term varchar (250)  NOT NULL,
	Definition varchar (5000)  NULL,
	Category varchar (250)  NULL,
	SourceVocabularyURI	 varchar (250)  NULL,
	PRIMARY KEY (Name)
)
CREATE TABLE CVs_VariableSpecific (
	Name varchar (250)  NOT NULL,
	Term varchar (250)  NOT NULL,
	Definition varchar (5000)  NULL,
	Category varchar (250)  NULL,
	SourceVocabularyURI varchar (250)  NULL,
	PRIMARY KEY (Name)
)
CREATE TABLE CVs_WaterAllocationBasis (
	Name varchar (250)  NOT NULL,
	Term varchar (250)  NOT NULL,
	Definition varchar (5000)  NULL,
	Category varchar (250)  NULL,
	SourceVocabularyURI	 varchar (250)  NULL,
	PRIMARY KEY (Name)
)
CREATE TABLE CVs_WaterQualityIndicator (
	Name varchar (250)  NOT NULL,
	Term varchar (250)  NOT NULL,
	Definition varchar (5000)  NULL,
	Category varchar (250)  NULL,
	SourceVocabularyURI	 varchar (250)  NULL,
	PRIMARY KEY (Name)
)
CREATE TABLE CVs_WaterSourceType (
	Name varchar (250)  NOT NULL,
	Term varchar (250)  NOT NULL,
	Definition varchar (5000)  NULL,
	Category varchar (250)  NULL,
	SourceVocabularyURI	 varchar (250)  NULL,
	PRIMARY KEY (Name)
)
CREATE TABLE Date_dim (
	DateID bigint   NOT NULL,
	Date date   NOT NULL,
	Year nchar (4)  NULL,
	PRIMARY KEY (DateID)
)
CREATE TABLE Methods_dim (
	MethodID bigint   NOT NULL,
	MethodUUID nvarchar (100)  NOT NULL,
	MethodName nvarchar (50)  NOT NULL,
	MethodDescription text   NOT NULL,
	MethodNEMILink nvarchar (100)  NULL,
	ApplicableResourceTypeCV nvarchar (100)  NOT NULL,
	MethodTypeCV nvarchar (50)  NOT NULL,
	DataCoverageValue nvarchar (100)  NULL,
	DataQualityValueCV nvarchar (50)  NULL,
	DataConfidenceValue nvarchar (50)  NULL,
	PRIMARY KEY (MethodID)
)
CREATE TABLE NHDMetadata (
	NHDMetadataID int   NOT NULL,
	NHDNetworkStatusCV varchar (50)  NOT NULL,
	NHDProductCV varchar (50)  NULL,
	NHDUpdateDate date   NULL,
	NHDReachCode varchar (50)  NULL,
	NHDMeasureNumber varchar (50)  NULL,
	PRIMARY KEY (NHDMetadataID)
)
CREATE TABLE NHDStatus (
	Name varchar (250)  NOT NULL,
	Term varchar (250)  NULL,
	Definition varchar (5000)  NULL,
	Category varchar (250)  NULL,
	SourceVocabularyURI varchar (250)  NULL,
	PRIMARY KEY (Name)
)
CREATE TABLE Organizations_dim (
	OrganizationID bigint   NOT NULL,
	OrganizationUUID nvarchar (250)  NOT NULL,
	OrganizationName nvarchar (250)  NOT NULL,
	OrganizationPurview nvarchar (250)  NULL,
	OrganizationWebsite nvarchar (250)  NOT NULL,
	OrganizationPhoneNumber nvarchar (250)  NOT NULL,
	OrganizationContactName nvarchar (250)  NOT NULL,
	OrganizationContactEmail nvarchar (250)  NOT NULL,
	PRIMARY KEY (OrganizationID)
)
CREATE TABLE RegulatoryOverlay_dim (
	RegulatoryOverlayID bigint   NOT NULL,
	RegulatoryOverlayUUID nvarchar (250)  NULL,
	RegulatoryOverlayNativeID nvarchar (250)  NULL,
	RegulatoryName nvarchar (50)  NOT NULL,
	RegulatoryDescription nvarchar(max)   NOT NULL,
	RegulatoryStatusCV nvarchar (50)  NOT NULL,
	OversightAgency nvarchar (250)  NOT NULL,
	RegulatoryStatute nvarchar (500)  NULL,
	RegulatoryStatuteLink varchar (500)  NULL,
	TimeframeStartID bigint   NOT NULL,
	TimeframeEndID bigint   NOT NULL,
	ReportYearTypeCV nvarchar (10)  NOT NULL,
	ReportYearStartMonth nvarchar (5)  NOT NULL,
	PRIMARY KEY (RegulatoryOverlayID)
)
CREATE TABLE RegulatoryReportingUnits_fact (
	BridgeID bigint   NOT NULL,
	RegulatoryOverlayID bigint   NOT NULL,
	OrganizationID bigint   NOT NULL,
	ReportingUnitID bigint   NOT NULL,
	DataPublicationDateID bigint   NOT NULL,
	ReportYearCV varchar (4)  NOT NULL,
	PRIMARY KEY (BridgeID)
)
CREATE TABLE ReportingUnits_dim (
	ReportingUnitID bigint   NOT NULL,
	ReportingUnitUUID nvarchar (250)  NOT NULL,
	ReportingUnitNativeID nvarchar (250)  NOT NULL,
	ReportingUnitName nvarchar (250)  NOT NULL,
	ReportingUnitTypeCV nvarchar (20)  NOT NULL,
	ReportingUnitUpdateDate date   NULL,
	ReportingUnitProductVersion nvarchar (100)  NULL,
	StateCV nvarchar (50)  NOT NULL,
	EPSGCodeCV nvarchar (50)  NULL,
	Geometry polygon   NULL,
	PRIMARY KEY (ReportingUnitID)
)
CREATE TABLE Sites_dim (
	SiteID bigint   NOT NULL,
	SiteUUID nvarchar (55)  NOT NULL,
	SiteNativeID nvarchar (50)  NULL,
	SiteName nvarchar (500)  NOT NULL,
	SiteTypeCV varchar (100)  NULL,
	Longitude nvarchar (50)  NOT NULL,
	Latitude nvarchar (50)  NOT NULL,
	SitePoint geometry   NULL,
	Geometry geometry   NULL,
	CoordinateMethodCV nvarchar (100)  NOT NULL,
	CoordinateAccuracy nvarchar (255)  NULL,
	GNISCodeCV nvarchar (50)  NULL,
	NHDMetadataID bigint   NULL,
	PRIMARY KEY (SiteID)
)
CREATE TABLE SitesBridge_BeneficialUses_fact (
	SiteBridgeID bigint   NOT NULL,
	BeneficialUseID bigint   NOT NULL,
	SiteVariableAmountID bigint   NOT NULL,
	PRIMARY KEY (SiteBridgeID)
)
CREATE TABLE SiteVariableAmounts_fact (
	SiteVariableAmountID bigint   NOT NULL,
	OrganizationID bigint   NOT NULL,
	AllocationID bigint   NULL,
	SiteID bigint   NOT NULL,
	VariableSpecificID bigint   NOT NULL,
	BeneficialUseID bigint   NOT NULL,
	WaterSourceID bigint   NOT NULL,
	MethodID bigint   NOT NULL,
	TimeframeStart bigint   NOT NULL,
	TimeframeEnd bigint   NOT NULL,
	DataPublicationDate bigint   NOT NULL,
	ReportYear nchar (4)  NULL,
	Amount float   NOT NULL,
	PopulationServed float   NULL,
	PowerGeneratedGWh float   NULL,
	IrrigatedAcreage float   NULL,
	IrrigationMethodCV nvarchar (100)  NULL,
	CropTypeCV nvarchar (100)  NULL,
	InterbasinTransferFromID nvarchar (100)  NULL,
	InterbasinTransferToID nvarchar (100)  NULL,
	Geometry geometry   NULL,
	PRIMARY KEY (SiteVariableAmountID)
)
CREATE TABLE Variables_dim (
	VariableSpecificID bigint   NOT NULL,
	VariableSpecificUUID nvarchar (250)  NULL,
	VariableSpecificCV nvarchar (250)  NOT NULL,
	VariableCV nvarchar (250)  NOT NULL,
	AggregationStatisticCV nvarchar (50)  NOT NULL,
	AggregationInterval  numeric (10)  NOT NULL,
	AggregationIntervalUnitCV  nvarchar (50)  NOT NULL,
	ReportYearStartMonth  nvarchar (10)  NOT NULL,
	ReportYearTypeCV  nvarchar (10)  NOT NULL,
	AmountUnitCV nvarchar (250)  NOT NULL,
	MaximumAmountUnitCV nvarchar (255)  NULL,
	PRIMARY KEY (VariableSpecificID)
)
CREATE TABLE WaterSources_dim (
	WaterSourceID bigint   NOT NULL,
	WaterSourceUUID nvarchar (100)  NOT NULL,
	WaterSourceNativeID nvarchar (250)  NULL,
	WaterSourceName nvarchar (250)  NULL,
	WaterSourceTypeCV nvarchar (100)  NOT NULL,
	WaterQualityIndicatorCV nvarchar (100)  NOT NULL,
	GNISFeatureNameCV nvarchar (250)  NULL,
	Geometry geometry   NULL,
	PRIMARY KEY (WaterSourceID)
)

ALTER TABLE AggBridge_BeneficialUses_fact ADD CONSTRAINT fk_AggBridge_BeneficialUses_fact_AggregatedAmounts_fact
FOREIGN KEY (AggregatedAmountID) REFERENCES AggregatedAmounts_fact (AggregatedAmountID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE AggBridge_BeneficialUses_fact ADD CONSTRAINT fk_AggBridge_BeneficialUses_fact_BeneficialUses_dim
FOREIGN KEY (BeneficialUseID) REFERENCES BeneficialUses_dim (BeneficialUseID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE AggregatedAmounts_fact ADD CONSTRAINT fk_AggregatedAmounts_Date_dim_end
FOREIGN KEY (TimeframeEndID) REFERENCES Date_dim (DateID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE AggregatedAmounts_fact ADD CONSTRAINT fk_AggregatedAmounts_Date_dim_end_pub
FOREIGN KEY (DataPublicationDate) REFERENCES Date_dim (DateID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE AggregatedAmounts_fact ADD CONSTRAINT fk_AggregatedAmounts_Date_dim_start
FOREIGN KEY (TimeframeStartID) REFERENCES Date_dim (DateID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE AggregatedAmounts_fact ADD CONSTRAINT fk_AggregatedAmounts_fact_BeneficialUses_dim
FOREIGN KEY (BeneficialUseID) REFERENCES BeneficialUses_dim (BeneficialUseID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE AggregatedAmounts_fact ADD CONSTRAINT fk_AggregatedAmounts_fact_CVs_ReportYearCV
FOREIGN KEY (ReportYear) REFERENCES CVs_ReportYearCV (Name)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE AggregatedAmounts_fact ADD CONSTRAINT fk_AggregatedAmounts_fact_Methods_dim
FOREIGN KEY (MethodID) REFERENCES Methods_dim (MethodID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE AggregatedAmounts_fact ADD CONSTRAINT fk_AggregatedAmounts_fact_Organizations_dim
FOREIGN KEY (OrganizationID) REFERENCES Organizations_dim (OrganizationID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE AggregatedAmounts_fact ADD CONSTRAINT fk_AggregatedAmounts_fact_ReportingUnits_dim
FOREIGN KEY (ReportingUnitID) REFERENCES ReportingUnits_dim (ReportingUnitID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE AggregatedAmounts_fact ADD CONSTRAINT fk_AggregatedAmounts_fact_Variables_dim
FOREIGN KEY (VariableSpecificID) REFERENCES Variables_dim (VariableSpecificID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE AggregatedAmounts_fact ADD CONSTRAINT fk_AggregatedAmounts_fact_WaterSources_dim
FOREIGN KEY (WaterSourceID) REFERENCES WaterSources_dim (WaterSourceID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE AllocationAmounts_fact ADD CONSTRAINT fk_AllocationAmounts_fact_Allocations_dim
FOREIGN KEY (AllocationID) REFERENCES Allocations_dim (AllocationID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE AllocationAmounts_fact ADD CONSTRAINT fk_AllocationAmounts_fact_BeneficialUses_dim
FOREIGN KEY (BeneficialUsesID) REFERENCES BeneficialUses_dim (BeneficialUseID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE AllocationAmounts_fact ADD CONSTRAINT fk_AllocationAmounts_fact_CVs_ReportYearCV
FOREIGN KEY (ReportYear) REFERENCES CVs_ReportYearCV (Name)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE AllocationAmounts_fact ADD CONSTRAINT fk_AllocationAmounts_fact_Date_dim_end
FOREIGN KEY (TimeframeEndDateID) REFERENCES Date_dim (DateID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE AllocationAmounts_fact ADD CONSTRAINT fk_AllocationAmounts_fact_Date_dim_start
FOREIGN KEY (TimeframeStartDateID) REFERENCES Date_dim (DateID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE AllocationAmounts_fact ADD CONSTRAINT fk_AllocationAmounts_fact_Date_pub
FOREIGN KEY (DataPublicationDateID) REFERENCES Date_dim (DateID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE AllocationAmounts_fact ADD CONSTRAINT fk_AllocationAmounts_fact_Methods_dim
FOREIGN KEY (MethodID) REFERENCES Methods_dim (MethodID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE AllocationAmounts_fact ADD CONSTRAINT fk_AllocationAmounts_fact_Organizations_dim
FOREIGN KEY (OrganizationID) REFERENCES Organizations_dim (OrganizationID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE AllocationAmounts_fact ADD CONSTRAINT fk_AllocationAmounts_fact_Sites_dim
FOREIGN KEY (SiteID) REFERENCES Sites_dim (SiteID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE AllocationAmounts_fact ADD CONSTRAINT fk_AllocationAmounts_fact_Variables_dim
FOREIGN KEY (VariableSpecificID) REFERENCES Variables_dim (VariableSpecificID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE AllocationAmounts_fact ADD CONSTRAINT fk_AllocationAmounts_fact_WaterSources_dim
FOREIGN KEY (WaterSourceID) REFERENCES WaterSources_dim (WaterSourceID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE AllocationBridge_BeneficialUses_fact ADD CONSTRAINT fk_AllocationBridge_BeneficialUses_fact_AllocationAmounts_fact
FOREIGN KEY (AllocationAmountID) REFERENCES AllocationAmounts_fact (AllocationAmountID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE AllocationBridge_BeneficialUses_fact ADD CONSTRAINT fk_AllocationBridge_BeneficialUses_fact_BeneficialUses_dim
FOREIGN KEY (BeneficialUseID) REFERENCES BeneficialUses_dim (BeneficialUseID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE Allocations_dim ADD CONSTRAINT fk_Allocations_dim_Date_dim_app
FOREIGN KEY (AllocationApplicationDate) REFERENCES Date_dim (DateID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE Allocations_dim ADD CONSTRAINT fk_Allocations_dim_Date_dim_exp
FOREIGN KEY (AllocationExpirationDate) REFERENCES Date_dim (DateID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE Allocations_dim ADD CONSTRAINT fk_Allocations_dim_Date_dim_prio
FOREIGN KEY (AllocationPriorityDate) REFERENCES Date_dim (DateID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE BeneficialUses_dim ADD CONSTRAINT fk_BeneficialUses_dim_CVs_NAICSCode
FOREIGN KEY (NAICSCodeNameCV) REFERENCES CVs_NAICSCode (Name)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE BeneficialUses_dim ADD CONSTRAINT fk_BeneficialUses_dim_CVs_USGSCategory
FOREIGN KEY (USGSCategoryNameCV) REFERENCES CVs_USGSCategory (Name)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE RegulatoryOverlay_dim ADD CONSTRAINT fk_RegulatoryOverlay_dim_Date_dim_end
FOREIGN KEY (TimeframeEndID) REFERENCES Date_dim (DateID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE RegulatoryOverlay_dim ADD CONSTRAINT fk_RegulatoryOverlay_dim_Date_dim_start
FOREIGN KEY (TimeframeStartID) REFERENCES Date_dim (DateID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE RegulatoryReportingUnits_fact ADD CONSTRAINT fk_RegulatoryReportingUnits_fact_Date_dim
FOREIGN KEY (DataPublicationDateID) REFERENCES Date_dim (DateID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE RegulatoryReportingUnits_fact ADD CONSTRAINT fk_RegulatoryReportingUnits_fact_Organizations_dim
FOREIGN KEY (OrganizationID) REFERENCES Organizations_dim (OrganizationID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE RegulatoryReportingUnits_fact ADD CONSTRAINT fk_RegulatoryReportingUnits_fact_RegulatoryOverlay_dim
FOREIGN KEY (RegulatoryOverlayID) REFERENCES RegulatoryOverlay_dim (RegulatoryOverlayID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE RegulatoryReportingUnits_fact ADD CONSTRAINT fk_RegulatoryReportingUnits_fact_ReportingUnits_dim
FOREIGN KEY (ReportingUnitID) REFERENCES ReportingUnits_dim (ReportingUnitID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE Sites_dim ADD CONSTRAINT fk_Sites_NHDMetadata
FOREIGN KEY (NHDMetadataID) REFERENCES NHDMetadata (NHDMetadataID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE SitesBridge_BeneficialUses_fact ADD CONSTRAINT fk_SitesBridge_BeneficialUses_fact_BeneficialUses_dim
FOREIGN KEY (BeneficialUseID) REFERENCES BeneficialUses_dim (BeneficialUseID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE SitesBridge_BeneficialUses_fact ADD CONSTRAINT fk_SitesBridge_BeneficialUses_fact_SiteVariableAmounts_fact
FOREIGN KEY (SiteVariableAmountID) REFERENCES SiteVariableAmounts_fact (SiteVariableAmountID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE SiteVariableAmounts_fact ADD CONSTRAINT fk_SiteVariableAmounts_Date_dim_end
FOREIGN KEY (TimeframeEnd) REFERENCES Date_dim (DateID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE SiteVariableAmounts_fact ADD CONSTRAINT fk_SiteVariableAmounts_Date_dim_pub
FOREIGN KEY (DataPublicationDate) REFERENCES Date_dim (DateID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE SiteVariableAmounts_fact ADD CONSTRAINT fk_SiteVariableAmounts_Date_dim_start
FOREIGN KEY (TimeframeStart) REFERENCES Date_dim (DateID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE SiteVariableAmounts_fact ADD CONSTRAINT fk_SiteVariableAmounts_fact_Allocations_dim
FOREIGN KEY (AllocationID) REFERENCES Allocations_dim (AllocationID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE SiteVariableAmounts_fact ADD CONSTRAINT fk_SiteVariableAmounts_fact_BeneficialUses_dim
FOREIGN KEY (BeneficialUseID) REFERENCES BeneficialUses_dim (BeneficialUseID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE SiteVariableAmounts_fact ADD CONSTRAINT fk_SiteVariableAmounts_fact_CVs_ReportYearCV
FOREIGN KEY (ReportYear) REFERENCES CVs_ReportYearCV (Name)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE SiteVariableAmounts_fact ADD CONSTRAINT fk_SiteVariableAmounts_fact_Methods_dim
FOREIGN KEY (MethodID) REFERENCES Methods_dim (MethodID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE SiteVariableAmounts_fact ADD CONSTRAINT fk_SiteVariableAmounts_fact_Organizations_dim
FOREIGN KEY (OrganizationID) REFERENCES Organizations_dim (OrganizationID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE SiteVariableAmounts_fact ADD CONSTRAINT fk_SiteVariableAmounts_fact_Sites_dim
FOREIGN KEY (SiteID) REFERENCES Sites_dim (SiteID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE SiteVariableAmounts_fact ADD CONSTRAINT fk_SiteVariableAmounts_fact_Variables_dim
FOREIGN KEY (VariableSpecificID) REFERENCES Variables_dim (VariableSpecificID)
ON UPDATE NO ACTION ON DELETE NO ACTION

ALTER TABLE SiteVariableAmounts_fact ADD CONSTRAINT fk_SiteVariableAmounts_fact_WaterSources_dim
FOREIGN KEY (WaterSourceID) REFERENCES WaterSources_dim (WaterSourceID)
ON UPDATE NO ACTION ON DELETE NO ACTION