-- Adel Abdallah, Senior Hydroinformatics Specialist at the WSWC, Feb 2019

--This is a Data Definition Language (DDL) script that
--generates a blank schema of the Water Data Exchange Data Model (WaDE)
-- for Microsoft SQL Server database.

-- Generated by Adel Abdallah Feb, 2019 based on WaDE XML design named WaDE2.0_schema_star generated by DbWrench V4.04 @ http://www.dbwrench.com/
-- WaDE All rights reserved. See BSD 3-Clause Licence @ https://github.com/WSWCWaterDataExchange/WaDE2.0/blob/master/LICENSE 

--Open PostgreSQL, click on Databases>> Postgers>>   at the left Object Browser panel
--Simply copy all this script and paste into the new window of "SQL query"
--Then click execute. The script should run successfully and create the 40 empty tables of WaDE"

--Adel has commented this part because it is not used in WaDE so far 
--CREATE EXTENSION if not exists postgis;
--CREATE EXTENSION if not exists postgis_topology;
--CREATE EXTENSION if not exists fuzzystrmatch;
--CREATE EXTENSION if not exists postgis_tiger_geoCoder;
-------------------------------------------------------------------------------

drop schema if exists WaDE cascade;

create schema WaDE;

/***************************************************************************/
/*************************** CREATE INPUTTABLES ****************************/
/***************************************************************************/

create table WaDE.AggregatedAmounts_VariableTable (
	organizationuuid varchar (250) NOT NULL primary key,
	reportingunitnativeid varchar (250) NOT NULL,
	variablespecificcv varchar (250) NOT NULL,
	beneficialusecategory varchar (500) NOT NULL,
	primaryusecategory varchar (250) NULL,
	allocationusgscategorycv varchar (250) NULL,
	watersourcenativeid varchar (250) NOT NULL,
	methodname varchar (250) NOT NULL,
	timeframestartdate date  NOT NULL,
	timeframeenddate date  NOT NULL,
	datapublicationdate date  NOT NULL,
	reportyear varchar (4) NOT NULL,
	amount double precision  NULL,
	populationserved double precision  NULL,
	powergeneratedgwh double precision  NULL,
	irrigatedacreage double precision  NULL,
	interbasintransferfromid varchar (250) NULL,
	interbasintransfertoid varchar (250) NULL
);
create table WaDE.AllocationAmounts_VariableTable (
	organizationuuid nvarchar (250) NOT NULL primary key,
	allocationnativeid nvarchar (250) NOT NULL,
	allocationowner nvarchar (250) NOT NULL,
	allocationbasiscv varchar (250) NULL,
	allocationlegalstatuscv nvarchar (250) NOT NULL,
	allocationapplicationdate date  NULL,
	allocationprioritydate date  NOT NULL,
	allocationexpirationdate date  NULL,
	allocationchangeapplicationindicator nvarchar (250) NULL,
	legacyallocationids nvarchar (250) NULL,
	sitenativeid nvarchar (250) NOT NULL,
	variablespecificcv nvarchar (250) NOT NULL,
	beneficialusecategory nvarchar (500) NOT NULL,
	primaryusecategory nvarchar (250) NULL,
	allocationusgscategorycv nvarchar (250) NULL,
	watersourcename nvarchar (250) NOT NULL,
	methodname nvarchar (250) NOT NULL,
	timeframestartdate date  NOT NULL,
	timeframeenddate date  NOT NULL,
	datapublicationdate date  NOT NULL,
	reportyear nchar (4) NOT NULL,
	allocationcropdutyamount double precision  NULL,
	allocationamount double precision  NULL,
	allocationmaximum double precision  NULL,
	populationserved double precision  NULL,
	powergeneratedgwh double precision  NULL,
	irrigatedacreage double precision  NULL,
	allocationcommunitywatersupplysystem nvarchar (250) NULL,
	sdwisidentifier nvarchar (250) NULL,
	geometry geometry  NULL
);
create table WaDE.BeneficialUses_dim_Input (
	beneficialusecategory nvarchar (500) NOT NULL primary key,
	primaryusecategory nvarchar (250) NULL,
	usgscategorynamecv nvarchar (250) NULL,
	naicscodenamecv nvarchar (250) NULL
);
create table WaDE.Methods_dim_input (
	methodname nvarchar (50) NOT NULL primary key,
	methoddescription text  NOT NULL,
	methodnemilink nvarchar (100) NULL,
	applicableresourcetypecv nvarchar (100) NOT NULL,
	methodtypecv nvarchar (50) NOT NULL,
	datacoveragevalue nvarchar (100) NULL,
	dataqualityvaluecv nvarchar (50) NULL,
	dataconfidencevalue nvarchar (50) NULL
);
create table WaDE.Organizations_dim_Input (
	organizationuuid nvarchar (250) NOT NULL primary key,
	organizationname nvarchar (250) NOT NULL,
	organizationpurview nvarchar (250) NULL,
	organizationwebsite nvarchar (250) NOT NULL,
	organizationphonenumber nvarchar (250) NOT NULL,
	organizationcontactname nvarchar (250) NOT NULL,
	organizationcontactemail nvarchar (250) NOT NULL
);
create table WaDE.RegulatoryOverlay_dim_input (
	regulatoryoverlaynativeid nvarchar (250) NOT NULL primary key,
	regulatoryname nvarchar (50) NOT NULL,
	regulatorydescription nvarchar(max)  NOT NULL,
	regulatorystatuscv nvarchar (50) NOT NULL,
	oversightagency nvarchar (250) NOT NULL,
	regulatorystatute nvarchar (500) NULL,
	regulatorystatutelink varchar (500) NULL,
	timeframestartid bigint  NOT NULL,
	timeframeendid bigint  NOT NULL,
	reportyeartypecv nvarchar (10) NOT NULL,
	reportyearstartmonth nvarchar (5) NOT NULL
);
create table WaDE.RegulatoryReportingUnits_VariableTable (
	regulatoryoverlayuuid varchar (250) NOT NULL primary key,
	organizationuuid varchar (250) NOT NULL,
	reportingunitnativeid varchar (250) NOT NULL,
	datapublicationdate date  NOT NULL,
	reportyearcv varchar (4) NOT NULL
);
create table WaDE.ReportingUnits_dim_Input (
	reportingunitnativeid nvarchar (250) NOT NULL primary key,
	reportingunitname nvarchar (250) NOT NULL,
	reportingunittypecv nvarchar (20) NOT NULL,
	reportingunitupdatedate date  NULL,
	reportingunitproductversion nvarchar (100) NULL,
	statecv nvarchar (50) NOT NULL,
	epsgcodecv nvarchar (50) NULL,
	geometry geometry  NULL
);
create table WaDE.Sites_dim_input (
	sitenativeid nvarchar (50) NOT NULL primary key,
	sitename nvarchar (500) NOT NULL,
	sitetypecv varchar (100) NULL,
	longitude nvarchar (50) NOT NULL,
	latitude nvarchar (50) NOT NULL,
	geometry geometry  NULL,
	coordinatemethodcv nvarchar (100) NOT NULL,
	coordinateaccuracy nvarchar (255) NULL,
	gniscodecv nvarchar (50) NULL
);
create table WaDE.SiteVariableAmounts_VariableTable (
	organizationuuid varchar (250) NOT NULL primary key,
	allocationuuid varchar (250) NULL,
	sitenativeid varchar (250) NOT NULL,
	variablespecificcv varchar (250) NOT NULL,
	beneficialusecategory varchar (500) NOT NULL,
	primaryusecategory varchar (250) NULL,
	allocationusgscategorycv varchar (250) NULL,
	watersourcenativeid varchar (250) NOT NULL,
	methodname varchar (250) NOT NULL,
	timeframestartdate date  NOT NULL,
	timeframeenddate date  NOT NULL,
	datapublicationdate date  NOT NULL,
	reportyear varchar (4) NOT NULL,
	amount double precision  NULL,
	populationserved double precision  NULL,
	powergeneratedgwh double precision  NULL,
	irrigatedacreage double precision  NULL,
	allocationcommunitywatersupplysystem varchar (250) NULL,
	sdwisidentifier varchar (250) NULL,
	interbasintransferfromid varchar (250) NULL,
	interbasintransfertoid varchar (250) NULL,
	geometry geometry  NULL
);
create table WaDE.Variables_dim_input (
	variablespecificcv nvarchar (250) NOT NULL primary key,
	variablecv nvarchar (250) NOT NULL,
	aggregationstatisticcv nvarchar (50) NOT NULL,
	aggregationinterval  numeric (10) NOT NULL,
	aggregationintervalunitcv  nvarchar (50) NOT NULL,
	reportyearstartmonth  nvarchar (10) NOT NULL,
	reportyeartypecv  nvarchar (10) NOT NULL,
	amountunitcv nvarchar (250) NOT NULL,
	maximumamountunitcv nvarchar (255) NULL
);
create table WaDE.WaterSources_dim_input (
	watersourcenativeid nvarchar (250) NOT NULL primary key,
	watersourcename nvarchar (250) NULL,
	watersourcetypecv nvarchar (100) NOT NULL,
	waterqualityindicatorcv nvarchar (100) NOT NULL,
	gnisfeaturenamecv nvarchar (250) NULL,
	geometry geometry  NULL
);
/***************************************************************************/
/**************************** CREATE WADE2_STAR ****************************/
/***************************************************************************/

create table WaDE.AggBridge_BeneficialUses_fact (
	aggbridgeid bigint  NOT NULL primary key,
	beneficialuseid bigint  NOT NULL,
	aggregatedamountid bigint  NOT NULL
);
create table WaDE.AggregatedAmounts_fact (
	aggregatedamountid bigint  NOT NULL primary key,
	organizationid bigint  NOT NULL,
	reportingunitid bigint  NOT NULL,
	variablespecificid bigint  NOT NULL,
	beneficialuseid bigint  NOT NULL,
	watersourceid bigint  NOT NULL,
	methodid bigint  NOT NULL,
	timeframestartid bigint  NULL,
	timeframeendid bigint  NULL,
	datapublicationdate bigint  NULL,
	reportyear nchar (4) NULL,
	amount double precision  NOT NULL,
	populationserved double precision  NULL,
	powergeneratedgwh double precision  NULL,
	irrigatedacreage double precision  NULL,
	interbasintransfertoid nvarchar (100) NULL,
	interbasintransferfromid nvarchar (100) NULL
);
create table WaDE.AllocationAmounts_fact (
	allocationamountid bigint  NOT NULL primary key,
	organizationid bigint  NOT NULL,
	allocationid bigint  NOT NULL,
	siteid bigint  NOT NULL,
	variablespecificid bigint  NOT NULL,
	beneficialusesid bigint  NOT NULL,
	watersourceid bigint  NOT NULL,
	methodid bigint  NOT NULL,
	timeframestartdateid bigint  NOT NULL,
	timeframeenddateid bigint  NOT NULL,
	datapublicationdateid bigint  NOT NULL,
	reportyear nchar (4) NOT NULL,
	allocationcropdutyamount double precision  NULL,
	allocationamount double precision  NULL,
	allocationmaximum double precision  NULL,
	populationserved double precision  NULL,
	powergeneratedgwh double precision  NULL,
	irrigatedacreage double precision  NULL,
	allocationcommunitywatersupplysystem nvarchar (250) NULL,
	sdwisidentifier nvarchar (250) NULL,
	geometry geometry  NULL
);
create table WaDE.AllocationBridge_BeneficialUses_fact (
	allocationbridgeid bigint  NOT NULL primary key,
	beneficialuseid bigint  NOT NULL,
	allocationamountid bigint  NOT NULL
);
create table WaDE.Allocations_dim (
	allocationid bigint  NOT NULL primary key,
	allocationuuid nvarchar (50) NOT NULL,
	allocationnativeid nvarchar (250) NOT NULL,
	allocationowner nvarchar (255) NOT NULL,
	allocationbasiscv nvarchar (250) NULL,
	allocationlegalstatuscv nvarchar (50) NOT NULL,
	allocationapplicationdate bigint  NULL,
	allocationprioritydate bigint  NOT NULL,
	allocationexpirationdate bigint  NULL,
	allocationchangeapplicationindicator nvarchar (100) NULL,
	legacyallocationids nvarchar (100) NULL
);
create table WaDE.Allocations_dim_Input (
	allocationnativeid nvarchar (250) NOT NULL primary key,
	allocationowner nvarchar (255) NOT NULL,
	allocationbasiscv nvarchar (250) NULL,
	allocationlegalstatuscv nvarchar (50) NOT NULL,
	allocationapplicationdate bigint  NULL,
	allocationprioritydate bigint  NOT NULL,
	allocationexpirationdate bigint  NULL,
	allocationchangeapplicationindicator nvarchar (100) NULL,
	legacyallocationids nvarchar (100) NULL
);
create table WaDE.BeneficialUses_dim (
	beneficialuseid bigint  NOT NULL primary key,
	beneficialuseuuid nvarchar (500) NULL,
	beneficialusecategory nvarchar (500) NOT NULL,
	primaryusecategory nvarchar (250) NULL,
	usgscategorynamecv nvarchar (250) NULL,
	naicscodenamecv nvarchar (250) NULL
);
create table WaDE.CVs_AggregationStatistic (
	name varchar (250) NOT NULL primary key,
	term varchar (250) NOT NULL,
	definition varchar (5000) NULL,
	category varchar (250) NULL,
	sourcevocabularyuri	 varchar (250) NULL
);
create table WaDE.CVs_CropType (
	name varchar (250) NOT NULL primary key,
	term varchar (250) NULL,
	definition varchar (5000) NULL,
	category varchar (250) NULL,
	sourcevocabularyuri varchar (250) NULL
);
create table WaDE.CVs_EPSGCode (
	name varchar (250) NOT NULL primary key,
	term varchar (250) NOT NULL,
	definition varchar (5000) NULL,
	category varchar (250) NULL,
	sourcevocabularyuri	 varchar (250) NULL
);
create table WaDE.CVs_GNISFeatureName (
	name varchar (250) NOT NULL primary key,
	term varchar (250) NOT NULL,
	definition varchar (5000) NULL,
	category varchar (250) NULL,
	sourcevocabularyuri	 varchar (250) NULL
);
create table WaDE.CVs_IrrigationMethod (
	name varchar (250) NOT NULL primary key,
	term varchar (250) NULL,
	definition varchar (5000) NULL,
	category varchar (250) NULL,
	sourcevocabularyuri varchar (250) NULL
);
create table WaDE.CVs_LegalStatus (
	name varchar (250) NOT NULL primary key,
	term varchar (250) NOT NULL,
	definition varchar (5000) NULL,
	category varchar (250) NULL,
	sourcevocabularyuri	 varchar (250) NULL
);
create table WaDE.CVs_MethodType (
	name varchar (250) NOT NULL primary key,
	term varchar (250) NOT NULL,
	definition varchar (5000) NULL,
	category varchar (250) NULL,
	sourcevocabularyuri	 varchar (250) NULL
);
create table WaDE.CVs_NAICSCode (
	name nvarchar (250) NOT NULL primary key,
	term nvarchar (250) NOT NULL,
	definition nvarchar(max)  NULL,
	category nvarchar (250) NULL,
	sourcevocabularyuri	 nvarchar (250) NULL
);
create table WaDE.CVs_NHDNetworkStatus (
	name varchar (250) NOT NULL primary key,
	term varchar (250) NOT NULL,
	definition varchar (5000) NULL,
	category varchar (250) NULL,
	sourcevocabularyuri	 varchar (250) NULL
);
create table WaDE.CVs_NHDProduct (
	name varchar (250) NOT NULL primary key,
	term varchar (250) NOT NULL,
	definition varchar (5000) NULL,
	category varchar (250) NULL,
	sourcevocabularyuri	 varchar (250) NULL
);
create table WaDE.CVs_RegulatoryStatus (
	name varchar (250) NOT NULL primary key,
	term varchar (250) NOT NULL,
	definition varchar (5000) NULL,
	category varchar (250) NULL,
	sourcevocabularyuri	 varchar (250) NULL
);
create table WaDE.CVs_ReportingUnitType (
	name varchar (250) NOT NULL primary key,
	term varchar (250) NOT NULL,
	definition varchar (5000) NULL,
	category varchar (250) NULL,
	sourcevocabularyuri	 varchar (250) NULL
);
create table WaDE.CVs_ReportYearCV (
	name nchar (4) NOT NULL primary key,
	term nvarchar (250) NOT NULL,
	definition nvarchar(max)  NULL,
	category nvarchar (250) NULL,
	sourcevocabularyuri	 nvarchar (250) NULL
);
create table WaDE.CVs_ReportYearType (
	name varchar (250) NOT NULL primary key,
	term varchar (250) NOT NULL,
	definition varchar (5000) NULL,
	category varchar (250) NULL,
	sourcevocabularyuri	 varchar (250) NULL
);
create table WaDE.CVs_Units (
	name varchar (250) NOT NULL primary key,
	term varchar (250) NOT NULL,
	definition varchar (5000) NULL,
	category varchar (250) NULL,
	sourcevocabularyuri	 varchar (250) NULL
);
create table WaDE.CVs_USGSCategory (
	name nvarchar (250) NOT NULL primary key,
	term nvarchar (250) NOT NULL,
	definition nvarchar(max)  NULL,
	category nvarchar (250) NULL,
	sourcevocabularyuri	 nvarchar (250) NULL
);
create table WaDE.CVs_Variable (
	name varchar (250) NOT NULL primary key,
	term varchar (250) NOT NULL,
	definition varchar (5000) NULL,
	category varchar (250) NULL,
	sourcevocabularyuri	 varchar (250) NULL
);
create table WaDE.CVs_VariableSpecific (
	name varchar (250) NOT NULL primary key,
	term varchar (250) NOT NULL,
	definition varchar (5000) NULL,
	category varchar (250) NULL,
	sourcevocabularyuri varchar (250) NULL
);
create table WaDE.CVs_WaterAllocationBasis (
	name varchar (250) NOT NULL primary key,
	term varchar (250) NOT NULL,
	definition varchar (5000) NULL,
	category varchar (250) NULL,
	sourcevocabularyuri	 varchar (250) NULL
);
create table WaDE.CVs_WaterQualityIndicator (
	name varchar (250) NOT NULL primary key,
	term varchar (250) NOT NULL,
	definition varchar (5000) NULL,
	category varchar (250) NULL,
	sourcevocabularyuri	 varchar (250) NULL
);
create table WaDE.CVs_WaterSourceType (
	name varchar (250) NOT NULL primary key,
	term varchar (250) NOT NULL,
	definition varchar (5000) NULL,
	category varchar (250) NULL,
	sourcevocabularyuri	 varchar (250) NULL
);
create table WaDE.Date_dim (
	dateid bigint  NOT NULL primary key,
	date date  NOT NULL,
	year nchar (4) NULL
);
create table WaDE.Methods_dim (
	methodid bigint  NOT NULL primary key,
	methoduuid nvarchar (100) NOT NULL,
	methodname nvarchar (50) NOT NULL,
	methoddescription text  NOT NULL,
	methodnemilink nvarchar (100) NULL,
	applicableresourcetypecv nvarchar (100) NOT NULL,
	methodtypecv nvarchar (50) NOT NULL,
	datacoveragevalue nvarchar (100) NULL,
	dataqualityvaluecv nvarchar (50) NULL,
	dataconfidencevalue nvarchar (50) NULL
);
create table WaDE.NHDMetadata (
	nhdmetadataid bigint  NOT NULL primary key,
	nhdnetworkstatuscv varchar (50) NOT NULL,
	nhdproductcv varchar (50) NULL,
	nhdupdatedate date  NULL,
	nhdreachcode varchar (50) NULL,
	nhdmeasurenumber varchar (50) NULL
);
create table WaDE.Organizations_dim (
	organizationid bigint  NOT NULL primary key,
	organizationuuid nvarchar (250) NOT NULL,
	organizationname nvarchar (250) NOT NULL,
	organizationpurview nvarchar (250) NULL,
	organizationwebsite nvarchar (250) NOT NULL,
	organizationphonenumber nvarchar (250) NOT NULL,
	organizationcontactname nvarchar (250) NOT NULL,
	organizationcontactemail nvarchar (250) NOT NULL
);
create table WaDE.RegulatoryOverlay_dim (
	regulatoryoverlayid bigint  NOT NULL primary key,
	regulatoryoverlayuuid nvarchar (250) NULL,
	regulatoryoverlaynativeid nvarchar (250) NULL,
	regulatoryname nvarchar (50) NOT NULL,
	regulatorydescription nvarchar(max)  NOT NULL,
	regulatorystatuscv nvarchar (50) NOT NULL,
	oversightagency nvarchar (250) NOT NULL,
	regulatorystatute nvarchar (500) NULL,
	regulatorystatutelink varchar (500) NULL,
	timeframestartid bigint  NOT NULL,
	timeframeendid bigint  NOT NULL,
	reportyeartypecv nvarchar (10) NOT NULL,
	reportyearstartmonth nvarchar (5) NOT NULL
);
create table WaDE.RegulatoryReportingUnits_fact (
	bridgeid bigint  NOT NULL primary key,
	regulatoryoverlayid bigint  NOT NULL,
	organizationid bigint  NOT NULL,
	reportingunitid bigint  NOT NULL,
	datapublicationdateid bigint  NOT NULL,
	reportyearcv nchar (4) NOT NULL
);
create table WaDE.ReportingUnits_dim (
	reportingunitid bigint  NOT NULL primary key,
	reportingunituuid nvarchar (250) NOT NULL,
	reportingunitnativeid nvarchar (250) NOT NULL,
	reportingunitname nvarchar (250) NOT NULL,
	reportingunittypecv nvarchar (20) NOT NULL,
	reportingunitupdatedate date  NULL,
	reportingunitproductversion nvarchar (100) NULL,
	statecv nvarchar (50) NOT NULL,
	epsgcodecv nvarchar (50) NULL,
	geometry geometry  NULL
);
create table WaDE.Sites_dim (
	siteid bigint  NOT NULL primary key,
	siteuuid nvarchar (55) NOT NULL,
	sitenativeid nvarchar (50) NULL,
	sitename nvarchar (500) NOT NULL,
	sitetypecv varchar (100) NULL,
	longitude nvarchar (50) NOT NULL,
	latitude nvarchar (50) NOT NULL,
	sitepoint geometry  NULL,
	geometry geometry  NULL,
	coordinatemethodcv nvarchar (100) NOT NULL,
	coordinateaccuracy nvarchar (255) NULL,
	gniscodecv nvarchar (50) NULL,
	nhdmetadataid bigint  NULL
);
create table WaDE.SitesBridge_BeneficialUses_fact (
	sitebridgeid bigint  NOT NULL primary key,
	beneficialuseid bigint  NOT NULL,
	sitevariableamountid bigint  NOT NULL
);
create table WaDE.SiteVariableAmounts_fact (
	sitevariableamountid bigint  NOT NULL primary key,
	organizationid bigint  NOT NULL,
	allocationid bigint  NULL,
	siteid bigint  NOT NULL,
	variablespecificid bigint  NOT NULL,
	beneficialuseid bigint  NOT NULL,
	watersourceid bigint  NOT NULL,
	methodid bigint  NOT NULL,
	timeframestart bigint  NOT NULL,
	timeframeend bigint  NOT NULL,
	datapublicationdate bigint  NOT NULL,
	reportyear nchar (4) NULL,
	amount double precision  NOT NULL,
	populationserved double precision  NULL,
	powergeneratedgwh double precision  NULL,
	irrigatedacreage double precision  NULL,
	irrigationmethodcv nvarchar (100) NULL,
	croptypecv nvarchar (100) NULL,
	interbasintransferfromid nvarchar (100) NULL,
	interbasintransfertoid nvarchar (100) NULL,
	geometry geometry  NULL
);
create table WaDE.Variables_dim (
	variablespecificid bigint  NOT NULL primary key,
	variablespecificuuid nvarchar (250) NULL,
	variablespecificcv nvarchar (250) NOT NULL,
	variablecv nvarchar (250) NOT NULL,
	aggregationstatisticcv nvarchar (50) NOT NULL,
	aggregationinterval  numeric (10) NOT NULL,
	aggregationintervalunitcv  nvarchar (50) NOT NULL,
	reportyearstartmonth  nvarchar (10) NOT NULL,
	reportyeartypecv  nvarchar (10) NOT NULL,
	amountunitcv nvarchar (250) NOT NULL,
	maximumamountunitcv nvarchar (255) NULL
);
create table WaDE.WaterSources_dim (
	watersourceid bigint  NOT NULL primary key,
	watersourceuuid nvarchar (100) NOT NULL,
	watersourcenativeid nvarchar (250) NULL,
	watersourcename nvarchar (250) NULL,
	watersourcetypecv nvarchar (100) NOT NULL,
	waterqualityindicatorcv nvarchar (100) NOT NULL,
	gnisfeaturenamecv nvarchar (250) NULL,
	geometry geometry  NULL
);

alter table WaDE.AggBridge_BeneficialUses_fact add constraint fk_AggBridge_BeneficialUses_fact_AggregatedAmounts_fact
foreign key (AggregatedAmountID) References WaDE.AggregatedAmounts_fact (AggregatedAmountID)
on update no Action on delete cascade;

alter table WaDE.AggBridge_BeneficialUses_fact add constraint fk_AggBridge_BeneficialUses_fact_BeneficialUses_dim
foreign key (BeneficialUseID) References WaDE.BeneficialUses_dim (BeneficialUseID)
on update no Action on delete cascade;

alter table WaDE.AggregatedAmounts_fact add constraint fk_AggregatedAmounts_Date_dim_end
foreign key (TimeframeEndID) References WaDE.Date_dim (DateID)
on update no Action on delete cascade;

alter table WaDE.AggregatedAmounts_fact add constraint fk_AggregatedAmounts_Date_dim_end_pub
foreign key (DataPublicationDate) References WaDE.Date_dim (DateID)
on update no Action on delete cascade;

alter table WaDE.AggregatedAmounts_fact add constraint fk_AggregatedAmounts_Date_dim_start
foreign key (TimeframeStartID) References WaDE.Date_dim (DateID)
on update no Action on delete cascade;

alter table WaDE.AggregatedAmounts_fact add constraint fk_AggregatedAmounts_fact_BeneficialUses_dim
foreign key (BeneficialUseID) References WaDE.BeneficialUses_dim (BeneficialUseID)
on update no Action on delete cascade;

alter table WaDE.AggregatedAmounts_fact add constraint fk_AggregatedAmounts_fact_CVs_ReportYearCV
foreign key (ReportYear) References WaDE.CVs_ReportYearCV (Name)
on update no Action on delete cascade;

alter table WaDE.AggregatedAmounts_fact add constraint fk_AggregatedAmounts_fact_Methods_dim
foreign key (MethodID) References WaDE.Methods_dim (MethodID)
on update no Action on delete cascade;

alter table WaDE.AggregatedAmounts_fact add constraint fk_AggregatedAmounts_fact_Organizations_dim
foreign key (OrganizationID) References WaDE.Organizations_dim (OrganizationID)
on update no Action on delete cascade;

alter table WaDE.AggregatedAmounts_fact add constraint fk_AggregatedAmounts_fact_ReportingUnits_dim
foreign key (ReportingUnitID) References WaDE.ReportingUnits_dim (ReportingUnitID)
on update no Action on delete cascade;

alter table WaDE.AggregatedAmounts_fact add constraint fk_AggregatedAmounts_fact_Variables_dim
foreign key (VariableSpecificID) References WaDE.Variables_dim (VariableSpecificID)
on update no Action on delete cascade;

alter table WaDE.AggregatedAmounts_fact add constraint fk_AggregatedAmounts_fact_WaterSources_dim
foreign key (WaterSourceID) References WaDE.WaterSources_dim (WaterSourceID)
on update no Action on delete cascade;

alter table WaDE.AllocationAmounts_fact add constraint fk_AllocationAmounts_fact_Allocations_dim
foreign key (AllocationID) References WaDE.Allocations_dim (AllocationID)
on update no Action on delete cascade;

alter table WaDE.AllocationAmounts_fact add constraint fk_AllocationAmounts_fact_BeneficialUses_dim
foreign key (BeneficialUsesID) References WaDE.BeneficialUses_dim (BeneficialUseID)
on update no Action on delete cascade;

alter table WaDE.AllocationAmounts_fact add constraint fk_AllocationAmounts_fact_CVs_ReportYearCV
foreign key (ReportYear) References WaDE.CVs_ReportYearCV (Name)
on update no Action on delete cascade;

alter table WaDE.AllocationAmounts_fact add constraint fk_AllocationAmounts_fact_Date_dim_end
foreign key (TimeframeEndDateID) References WaDE.Date_dim (DateID)
on update no Action on delete cascade;

alter table WaDE.AllocationAmounts_fact add constraint fk_AllocationAmounts_fact_Date_dim_start
foreign key (TimeframeStartDateID) References WaDE.Date_dim (DateID)
on update no Action on delete cascade;

alter table WaDE.AllocationAmounts_fact add constraint fk_AllocationAmounts_fact_Date_pub
foreign key (DataPublicationDateID) References WaDE.Date_dim (DateID)
on update no Action on delete cascade;

alter table WaDE.AllocationAmounts_fact add constraint fk_AllocationAmounts_fact_Methods_dim
foreign key (MethodID) References WaDE.Methods_dim (MethodID)
on update no Action on delete cascade;

alter table WaDE.AllocationAmounts_fact add constraint fk_AllocationAmounts_fact_Organizations_dim
foreign key (OrganizationID) References WaDE.Organizations_dim (OrganizationID)
on update no Action on delete cascade;

alter table WaDE.AllocationAmounts_fact add constraint fk_AllocationAmounts_fact_Sites_dim
foreign key (SiteID) References WaDE.Sites_dim (SiteID)
on update no Action on delete cascade;

alter table WaDE.AllocationAmounts_fact add constraint fk_AllocationAmounts_fact_Variables_dim
foreign key (VariableSpecificID) References WaDE.Variables_dim (VariableSpecificID)
on update no Action on delete cascade;

alter table WaDE.AllocationAmounts_fact add constraint fk_AllocationAmounts_fact_WaterSources_dim
foreign key (WaterSourceID) References WaDE.WaterSources_dim (WaterSourceID)
on update no Action on delete cascade;

alter table WaDE.AllocationBridge_BeneficialUses_fact add constraint fk_AllocationBridge_BeneficialUses_fact_AllocationAmounts_fact
foreign key (AllocationAmountID) References WaDE.AllocationAmounts_fact (AllocationAmountID)
on update no Action on delete cascade;

alter table WaDE.AllocationBridge_BeneficialUses_fact add constraint fk_AllocationBridge_BeneficialUses_fact_BeneficialUses_dim
foreign key (BeneficialUseID) References WaDE.BeneficialUses_dim (BeneficialUseID)
on update no Action on delete cascade;

alter table WaDE.Allocations_dim add constraint fk_Allocations_dim_Date_dim_app
foreign key (AllocationApplicationDate) References WaDE.Date_dim (DateID)
on update no Action on delete cascade;

alter table WaDE.Allocations_dim add constraint fk_Allocations_dim_Date_dim_exp
foreign key (AllocationExpirationDate) References WaDE.Date_dim (DateID)
on update no Action on delete cascade;

alter table WaDE.Allocations_dim add constraint fk_Allocations_dim_Date_dim_prio
foreign key (AllocationPriorityDate) References WaDE.Date_dim (DateID)
on update no Action on delete cascade;

alter table WaDE.BeneficialUses_dim add constraint fk_BeneficialUses_dim_CVs_NAICSCode
foreign key (NAICSCodeNameCV) References WaDE.CVs_NAICSCode (Name)
on update no Action on delete cascade;

alter table WaDE.BeneficialUses_dim add constraint fk_BeneficialUses_dim_CVs_USGSCategory
foreign key (USGSCategoryNameCV) References WaDE.CVs_USGSCategory (Name)
on update no Action on delete cascade;

alter table WaDE.RegulatoryOverlay_dim add constraint fk_RegulatoryOverlay_dim_Date_dim_end
foreign key (TimeframeEndID) References WaDE.Date_dim (DateID)
on update no Action on delete cascade;

alter table WaDE.RegulatoryOverlay_dim add constraint fk_RegulatoryOverlay_dim_Date_dim_start
foreign key (TimeframeStartID) References WaDE.Date_dim (DateID)
on update no Action on delete cascade;

alter table WaDE.RegulatoryReportingUnits_fact add constraint fk_RegulatoryReportingUnits_fact_Date_dim
foreign key (DataPublicationDateID) References WaDE.Date_dim (DateID)
on update no Action on delete cascade;

alter table WaDE.RegulatoryReportingUnits_fact add constraint fk_RegulatoryReportingUnits_fact_Organizations_dim
foreign key (OrganizationID) References WaDE.Organizations_dim (OrganizationID)
on update no Action on delete cascade;

alter table WaDE.RegulatoryReportingUnits_fact add constraint fk_RegulatoryReportingUnits_fact_RegulatoryOverlay_dim
foreign key (RegulatoryOverlayID) References WaDE.RegulatoryOverlay_dim (RegulatoryOverlayID)
on update no Action on delete cascade;

alter table WaDE.RegulatoryReportingUnits_fact add constraint fk_RegulatoryReportingUnits_fact_ReportingUnits_dim
foreign key (ReportingUnitID) References WaDE.ReportingUnits_dim (ReportingUnitID)
on update no Action on delete cascade;

alter table WaDE.Sites_dim add constraint fk_Sites_NHDMetadata
foreign key (NHDMetadataID) References WaDE.NHDMetadata (NHDMetadataID)
on update no Action on delete cascade;

alter table WaDE.SitesBridge_BeneficialUses_fact add constraint fk_SitesBridge_BeneficialUses_fact_BeneficialUses_dim
foreign key (BeneficialUseID) References WaDE.BeneficialUses_dim (BeneficialUseID)
on update no Action on delete cascade;

alter table WaDE.SitesBridge_BeneficialUses_fact add constraint fk_SitesBridge_BeneficialUses_fact_SiteVariableAmounts_fact
foreign key (SiteVariableAmountID) References WaDE.SiteVariableAmounts_fact (SiteVariableAmountID)
on update no Action on delete cascade;

alter table WaDE.SiteVariableAmounts_fact add constraint fk_SiteVariableAmounts_Date_dim_end
foreign key (TimeframeEnd) References WaDE.Date_dim (DateID)
on update no Action on delete cascade;

alter table WaDE.SiteVariableAmounts_fact add constraint fk_SiteVariableAmounts_Date_dim_pub
foreign key (DataPublicationDate) References WaDE.Date_dim (DateID)
on update no Action on delete cascade;

alter table WaDE.SiteVariableAmounts_fact add constraint fk_SiteVariableAmounts_Date_dim_start
foreign key (TimeframeStart) References WaDE.Date_dim (DateID)
on update no Action on delete cascade;

alter table WaDE.SiteVariableAmounts_fact add constraint fk_SiteVariableAmounts_fact_Allocations_dim
foreign key (AllocationID) References WaDE.Allocations_dim (AllocationID)
on update no Action on delete cascade;

alter table WaDE.SiteVariableAmounts_fact add constraint fk_SiteVariableAmounts_fact_BeneficialUses_dim
foreign key (BeneficialUseID) References WaDE.BeneficialUses_dim (BeneficialUseID)
on update no Action on delete cascade;

alter table WaDE.SiteVariableAmounts_fact add constraint fk_SiteVariableAmounts_fact_CVs_ReportYearCV
foreign key (ReportYear) References WaDE.CVs_ReportYearCV (Name)
on update no Action on delete cascade;

alter table WaDE.SiteVariableAmounts_fact add constraint fk_SiteVariableAmounts_fact_Methods_dim
foreign key (MethodID) References WaDE.Methods_dim (MethodID)
on update no Action on delete cascade;

alter table WaDE.SiteVariableAmounts_fact add constraint fk_SiteVariableAmounts_fact_Organizations_dim
foreign key (OrganizationID) References WaDE.Organizations_dim (OrganizationID)
on update no Action on delete cascade;

alter table WaDE.SiteVariableAmounts_fact add constraint fk_SiteVariableAmounts_fact_Sites_dim
foreign key (SiteID) References WaDE.Sites_dim (SiteID)
on update no Action on delete cascade;

alter table WaDE.SiteVariableAmounts_fact add constraint fk_SiteVariableAmounts_fact_Variables_dim
foreign key (VariableSpecificID) References WaDE.Variables_dim (VariableSpecificID)
on update no Action on delete cascade;

alter table WaDE.SiteVariableAmounts_fact add constraint fk_SiteVariableAmounts_fact_WaterSources_dim
foreign key (WaterSourceID) References WaDE.WaterSources_dim (WaterSourceID)
on update no Action on delete cascade;