on:
  push:
    branches:
      - master
name: Deploy Application to Staging/Production

env:
  API_HOST:  https://wade-api.azure-api.net/api/v2

jobs:
  artifact-swagger:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Update swagger.json server url
        run: echo "`jq '.servers[0].url="${{ env.API_HOST }}"' swagger.json`" > swagger.json
        working-directory: ./source/WaDEApiFunctions/v2

      - name: Read swagger.json
        run: cat swagger.json
        working-directory: ./source/WaDEApiFunctions/v2

      - name: Artifact swagger.json
        uses: actions/upload-artifact@v2
        with:
          name: swagger.json
          path: ./source/WaDEApiFunctions/v2/swagger.json

  call-deploy-app-staging:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: Staging
    secrets: inherit

  call-deploy-app-production:
    uses: ./.github/workflows/deploy.yml
    needs: call-deploy-app-staging
    with:
      environment: Prod
    secrets: inherit