on:
  workflow_dispatch:  
  push:
    branches:
      - develop
name: Deploy Application to QA

jobs:
  call-deploy-app-staging:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: QA
    secrets: inherit