on:
  workflow_dispatch:  
  push:
    branches:
      - develop
name: Deploy Application to QA

jobs:
  deploy-backend:
    uses: ./.github/workflows/deploy.yml
    with:
      azure-api-name: ogc-api
      azure-api-url: https://wadeazurefunctions-qa.azurewebsites.net/api
      azure-apim-name: WADE-API-QA
      azure-cors-domain: N/A
      azure-functionapp-name: WaDEAzureFunctions-QA
      azure-resource-group: WaDE_QA
      environment: QA
    secrets: inherit