name: PR Backend

on:
  pull_request:
    branches: [ develop, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: source

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: create-database-container
      run: docker-compose -f ci-compose.yml up -d
      working-directory: .github

    - name: setup-dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: restore-dependencies
      run: dotnet restore

    - name: build-solution
      run: dotnet build --no-restore

    - name: create-database
      run: docker exec -i mssql /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'DevP@ssw0rd!' -Q 'create database WaDE2'

    - name: update-database
      run: dotnet run --args "Server=localhost; Initial Catalog=WaDE2; User=sa; Password=DevP@ssw0rd!;"
      working-directory: source/WesternStatesWater.WaDE.DbUp

    #Running tests suites individually because running them all at once causes test abort issues in GitHub Actions 🤷🏽
    - name: run-accessor-tests
      run: dotnet test
      working-directory: source/WesternStatesWater.WaDE.Accessors.Tests
      env:
          ConnectionStrings__WadeDatabase: "Server=localhost; Initial Catalog=WaDE2; User=sa; Password=DevP@ssw0rd!; MultipleActiveResultSets=False;"
    
    - name: run-client-tests
      run: dotnet test
      working-directory: source/WesternStatesWater.WaDE.Clients.Tests
    
    - name: run-manager-tests
      run: dotnet test
      working-directory: source/WesternStatesWater.WaDE.Managers.Tests
    
    - name: run-utility-tests
      run: dotnet test
      working-directory: source/WesternStatesWater.WaDE.Utilities.Tests
